const KEY='rakutenTravelPerformanceAssistantV1';
const ANGLES=[['food','料理'],['onsen','温泉・露天風呂'],['room','部屋・眺望'],['family','子連れ・家族旅行'],['couple','夫婦・カップル'],['themepark','テーマパーク周辺'],['location','観光・立地'],['season','季節・イベント'],['coupon','クーポン・割引'],['limited','期間限定プラン'],['ranking','ランキング・評価'],['transport','交通とのセット']];
const L={unverified:'未確認',verified:'公式確認済み',expired:'期限切れ',recheck:'要再確認',draft:'下書き',ready:'投稿準備完了',posted:'投稿済み',reply_link:'本文＋リンク付き返信',direct_link:'本文に直接リンク',multi_reply:'本文＋返信1＋返信2',natural:'自然',strong:'少し強め'};
let state=load(), drafts={}, currentRakutenSelection=null;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])), fmt=n=>n===''||n==null?'未入力':Number(n).toLocaleString('ja-JP');
function load(){try{let raw=localStorage.getItem(KEY);if(!raw){let d={settings:{},candidates:[],history:[],sales:[]};localStorage.setItem(KEY,JSON.stringify(d));return d}let d=JSON.parse(raw);if(d&&typeof d==='object'&&d.settings&&Array.isArray(d.candidates)&&Array.isArray(d.history)&&Array.isArray(d.sales))return d}catch(e){}return {settings:{},candidates:[],history:[],sales:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function notice(t){$('notice').textContent=t;setTimeout(()=>{$('notice').textContent=''},3000)}
function copyTextWithFeedback(text,{button=null,status=null,label=''}={}){const value=String(text??'').trim();if(!value){if(status)status.textContent='コピーする内容がありません。';return Promise.resolve(false)}const success=()=>{if(button){button.textContent='コピーしました';clearTimeout(button._copyTimer);button._copyTimer=setTimeout(()=>{button.textContent=label},2500)}if(status){status.textContent='コピーしました';clearTimeout(status._copyTimer);status._copyTimer=setTimeout(()=>{status.textContent=''},2500)}return true};const failure=()=>{if(button){button.textContent='コピーできませんでした';clearTimeout(button._copyTimer);button._copyTimer=setTimeout(()=>{button.textContent=label},2500)}if(status){status.textContent='コピーできませんでした';clearTimeout(status._copyTimer);status._copyTimer=setTimeout(()=>{status.textContent=''},2500)}return false};if(!navigator.clipboard?.writeText)return Promise.resolve(failure());return navigator.clipboard.writeText(value).then(success).catch(failure)}
function sum(rows,k){return rows.reduce((a,r)=>a+(r.metrics?.[k]==null||r.metrics?.[k]===''?0:Number(r.metrics[k])||0),0)}
function nav(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));render()}
function render(){renderStats();renderCandidates();renderHistory();renderAnalysis()}
function renderStats(){let p=state.candidates.filter(c=>c.status==='posted'),a=[['投稿候補数',state.candidates.length],['投稿済み数',p.length],['総本文表示数',sum(p,'impressions')],['総クリック数',sum(p,'clicks')],['予約成果件数',sum(p,'bookings')],['総報酬額',sum(p,'reward')]];$('stats').innerHTML=a.map(x=>'<div class="stat"><strong>'+fmt(x[1])+'</strong><span>'+x[0]+'</span></div>').join('')}
function renderCandidates(){let b=$('candidate-list');if(!state.candidates.length){b.innerHTML='<div class="empty">旅行情報を登録すると、ここに投稿候補が表示されます。</div>';return}b.innerHTML=state.candidates.map(c=>'<article class="card"><h3>'+esc(c.facilityName)+'</h3><div class="card-meta"><span>'+esc([c.prefecture,c.region].filter(Boolean).join('・'))+'</span><span class="badge">'+(L[c.angle]||'切り口未選択')+'</span><span class="badge '+(c.verificationStatus==='verified'?'good':'warn')+'">'+L[c.verificationStatus]+'</span><span class="badge">'+L[c.status]+'</span></div><p class="muted">作成：'+new Date(c.createdAt).toLocaleString('ja-JP')+'</p>'+(c.verificationStatus!=='verified'?'<div class="warning">未確認情報があります。価格・割引・期限は公式確認後に使用してください。</div>':'')+'<div class="card-actions"><button class="primary" data-a="compose" data-id="'+c.id+'">投稿を作成</button><button class="secondary" data-a="edit" data-id="'+c.id+'">詳細・編集</button><button class="danger" data-a="delete" data-id="'+c.id+'">削除</button></div><div id="compose-'+c.id+'"></div>'+(c.status==='posted'?metrics(c):'')+'</article>').join('')}
function metrics(c){let m=c.metrics||{};return '<details class="panel"><summary>成果を入力・更新</summary><div class="inline-form">'+[['impressions','本文表示数'],['replyImpressions','返信1表示数'],['reply2Impressions','返信2表示数'],['likes','本文いいね'],['replyLikes','返信いいね'],['replies','返信数'],['reposts','再投稿数'],['clicks','クリック数'],['bookings','予約成果件数'],['sales','売上額'],['reward','報酬額']].map(x=>'<label>'+x[1]+'<input type="number" min="0" data-metric="'+x[0]+'" data-id="'+c.id+'" value="'+(m[x[0]]??'')+'"></label>').join('')+'</div></details>'}
function renderHistory(){let b=$('history-list');b.innerHTML=state.history.length?state.history.map(h=>'<article class="card"><h3>'+esc(h.facilityName)+'</h3><div class="card-meta"><span>'+L[h.format]+'</span><span>'+new Date(h.postedAt).toLocaleString('ja-JP')+'</span></div><details><summary>投稿内容</summary><p>'+esc(h.body).replaceAll('\n','<br>')+'</p><p>'+esc(h.reply1).replaceAll('\n','<br>')+'</p>'+(h.reply2?'<p>'+esc(h.reply2).replaceAll('\n','<br>')+'</p>':'')+'</details></article>').join(''):'<div class="empty">投稿済みの履歴はありません。</div>'}
function renderAnalysis(){let rows=[['format','投稿形式別',Object.keys({reply_link:1,direct_link:1,multi_reply:1})],['angle','切り口別',ANGLES.map(x=>x[0])]];$('analysis-content').innerHTML=rows.map(r=>'<div class="panel"><h3>'+r[1]+'</h3><table class="metric-table"><thead><tr><th>分類</th><th>投稿数</th><th>本文表示数</th><th>クリック数</th><th>予約成果</th><th>報酬額</th><th>CTR</th></tr></thead><tbody>'+r[2].map(k=>{let rs=state.history.filter(h=>h[r[0]]===k),i=sum(rs,'impressions'),cl=sum(rs,'clicks'),label=r[0]==='angle'?(ANGLES.find(x=>x[0]===k)||[k,k])[1]:L[k];return '<tr><td>'+label+'</td><td>'+rs.length+'</td><td>'+fmt(i)+'</td><td>'+fmt(cl)+'</td><td>'+fmt(sum(rs,'bookings'))+'</td><td>'+fmt(sum(rs,'reward'))+'</td><td>'+(i?(cl/i*100).toFixed(2)+'%':'未計算')+'</td></tr>'}).join('')+'</tbody></table></div>').join('')}
function clearForm(){if(!$('travel-form'))return;$('travel-form').reset();currentRakutenSelection=null;if($('rakuten-search-keyword'))$('rakuten-search-keyword').value='';if($('rakuten-search-status'))$('rakuten-search-status').textContent='';if($('rakuten-search-results'))$('rakuten-search-results').innerHTML='';$('edit-id').value='';$('form-title').textContent='旅行情報を登録';$('experience').value='none';$('verificationStatus').value='unverified'}
function dataFromForm(){let ids=['facilityName','prefecture','region','purpose','targetAudience','attraction','currentPrice','regularPrice','targetDate','stayPeriod','bookingDeadline','couponDeadline','campaignPeriod','checkedAt','stayConditions','coupon','couponConditions','campaign','campaignConditions','notes','sourceUrl','affiliateUrl','threadsShortUrl','experience','verificationStatus'],d={};ids.forEach(i=>{const el=$(i);if(el)d[i]=el.value.trim()});d.postCategory=$('postCategory')?.value||'hotel';d.dealType=$('deal-panel')?.querySelector('input[name="dealType"]:checked')?.value||'discountRate';d.discountRate=$('dealDiscountRate')?.value.trim()||'';d.discountAmount=$('dealDiscountAmount')?.value.trim()||'';d.dealText=$('dealText')?.value.trim()||'';d.dealDeadline=$('dealDeadline')?.value.trim()||'';d.dealConditions=$('dealConditions')?.value.trim()||'';d.couponUrl=$('couponUrl')?.value.trim()||'';d.campaignName=$('campaignName')?.value.trim()||'';d.campaignRegion=$('campaignRegion')?.value.trim()||'';d.discountText=$('discountText')?.value.trim()||'';d.startAt=$('startAt')?.value.trim()||'';d.endAt=$('endAt')?.value.trim()||'';d.isFirstCome=Boolean($('isFirstCome')?.checked);d.firstComeCondition=$('firstComeCondition')?.value.trim()||'';d.campaignConditions=$('campaignConditionsNew')?.value.trim()||'';d.campaignNotes=$('campaignNotes')?.value.trim()||'';['currentPrice','regularPrice','discountAmount','discountRate'].forEach(i=>{if(d[i]!=='')d[i]=Number(d[i])});return d}
function generate(c,tone='natural',format='reply_link'){if(c.postCategory==='campaign'){const confirmed=c.verificationStatus==='verified',name=c.campaignName||'楽天トラベルのキャンペーン',region=c.campaignRegion||'対象地域',discount=confirmed?(c.discountText||'お得なキャンペーン'):'公式情報を確認中のキャンペーン',start=confirmed&&c.startAt?'利用開始：'+c.startAt:'',end=confirmed&&c.endAt?'終了：'+c.endAt:'',first=confirmed&&c.isFirstCome?(c.firstComeCondition||'先着順'):'',conditions=confirmed&&c.campaignConditions?'対象条件：'+c.campaignConditions:'',link=c.threadsShortUrl||'',body=region+'旅行を考えている方へ。\n'+discount+'のキャンペーンが'+(start||'予定されています')+'。\n'+(first?'先着順のため、条件を事前に確認しておくとよさそうです。':'利用条件は公式情報をご確認ください。'),reply1=[name,discount,start,end,first,conditions,'対象施設・詳しい条件はこちら👇',link,link?'PR':''].filter(Boolean).join('\n');return {body,reply1,reply2:confirmed&&c.campaignNotes?c.campaignNotes:''}}let who=c.targetAudience||'旅行を検討している人',place=[c.facilityName,c.region,c.prefecture].filter(Boolean).join('・'),link=c.threadsShortUrl||'',deal=c.dealType==='discountRate'&&c.discountRate!==''?c.discountRate+'%OFF':c.dealType==='discountAmount'&&c.discountAmount!==''?fmt(c.discountAmount)+'円OFF':c.dealText||'',dealLine=(deal?'お得情報：'+deal+'。\n':'')+(c.dealDeadline?'【期限：'+c.dealDeadline+'】\n':'')+(c.dealConditions?c.dealConditions+'\n':''),lead=tone==='strong'?'候補に入れてみてもよさそうです。':'条件に合うか、公式情報を確認してみてください。',body=dealLine+who+'向けに、'+(place||'楽天トラベルの宿泊情報')+'をチェック。\n'+(c.attraction||'公式情報を確認しながら、旅の予定を考えられる情報')+'。\n'+lead,facts=[];if(c.verificationStatus==='verified'){if(c.currentPrice)facts.push('現在料金：'+fmt(c.currentPrice)+'円');if(c.regularPrice)facts.push('通常料金：'+fmt(c.regularPrice)+'円');if(c.discountAmount)facts.push('割引額：'+fmt(c.discountAmount)+'円');if(c.discountRate)facts.push('割引率：'+c.discountRate+'%');if(c.coupon)facts.push('クーポン：'+c.coupon);if(c.bookingDeadline)facts.push('予約期限：'+c.bookingDeadline)}if(format==='direct_link'&&link)body+='\n'+link;return {body,reply1:[place||'詳細情報',dealLine.trim(),facts.join('／'),link,link?'PR':''].filter(Boolean).join('\n'),reply2:[c.dealConditions,c.stayConditions,c.couponConditions,c.campaignConditions,c.notes].filter(Boolean).join('\n')}}
function compose(c){let d=drafts[c.id]||{angle:'location',tone:'natural',format:'reply_link'},g=generate(c,d.tone,d.format);drafts[c.id]={...d,...g};let x=drafts[c.id];$('compose-'+c.id).innerHTML='<div class="panel"><h3>投稿内容を作成</h3>'+(c.verificationStatus!=='verified'?'<div class="warning">未確認情報は確定情報として使用していません。</div>':'')+'<div class="grid three"><label>切り口<select data-c="angle" data-id="'+c.id+'">'+ANGLES.map(a=>'<option value="'+a[0]+'" '+(x.angle===a[0]?'selected':'')+'>'+a[1]+'</option>').join('')+'</select></label><label>トーン<select data-c="tone" data-id="'+c.id+'"><option value="natural" '+(x.tone==='natural'?'selected':'')+'>自然</option><option value="strong" '+(x.tone==='strong'?'selected':'')+'>少し強め</option></select></label><label>投稿形式<select data-c="format" data-id="'+c.id+'"><option value="reply_link" '+(x.format==='reply_link'?'selected':'')+'>本文＋リンク付き返信</option><option value="direct_link" '+(x.format==='direct_link'?'selected':'')+'>本文に直接リンク</option><option value="multi_reply" '+(x.format==='multi_reply'?'selected':'')+'>本文＋返信1＋返信2</option></select></label></div><div class="generated"><label>本文<textarea data-t="body" data-id="'+c.id+'" rows="5">'+esc(x.body)+'</textarea><button class="secondary copy" data-tcopy="body" data-id="'+c.id+'">本文をコピー</button><label>返信1<textarea data-t="reply1" data-id="'+c.id+'" rows="4">'+esc(x.reply1)+'</textarea><button class="secondary copy" data-tcopy="reply1" data-id="'+c.id+'">返信1をコピー</button>'+(x.format==='multi_reply'?'<label>返信2<textarea data-t="reply2" data-id="'+c.id+'" rows="4">'+esc(x.reply2)+'</textarea><button class="secondary copy" data-tcopy="reply2" data-id="'+c.id+'">返信2をコピー</button>':'')+'</div><div class="card-actions"><button class="primary" data-a="ready" data-id="'+c.id+'">投稿準備完了として保存</button><button class="secondary" data-a="posted" data-id="'+c.id+'">投稿済みにする</button></div></div>'}
function sync(id){document.querySelectorAll('[data-t][data-id="'+id+'"]').forEach(x=>drafts[id][x.dataset.t]=x.value)}
function validHttpUrl(value){return !value||/^https?:\/\//i.test(value)}
document.addEventListener('click',e=>{if(e.target.dataset.view)nav(e.target.dataset.view);let a=e.target.dataset.a,id=e.target.dataset.id,c=state.candidates.find(x=>x.id===id);if(a==='compose')compose(c);if(a==='edit'){Object.keys(c).forEach(k=>{if($(k))$(k).value=c[k]??''});$('edit-id').value=id;$('form-title').textContent='旅行情報を編集';nav('travel')}if(a==='delete'&&confirm('この旅行情報を削除しますか？')){state.candidates=state.candidates.filter(x=>x.id!==id);state.history=state.history.filter(x=>x.candidateId!==id);save()}if(a==='ready'||a==='posted'){sync(id);if(c.threadsShortUrl&&!validHttpUrl(c.threadsShortUrl)){notice('Threads用短縮URLはhttp://またはhttps://で入力してください。');return}if(c.affiliateUrl&&!c.threadsShortUrl){notice('Threads用短縮URLを入力してください。長いURLは投稿文へ自動使用しません。');return}if(a==='posted'&&c.affiliateUrl&&!/PR|※PR/.test((drafts[id].body||'')+(drafts[id].reply1||''))){notice('アフィリエイトURLがあるため、PR表示を入れてください。');return}c.status=a==='posted'?'posted':'ready';c.angle=drafts[id].angle;c.tone=drafts[id].tone;c.format=drafts[id].format;c.post={...drafts[id]};if(a==='posted'){c.postedAt=new Date().toISOString();c.metrics=c.metrics||{};state.history=state.history.filter(h=>h.candidateId!==id);state.history.push({...c,candidateId:id,postFormat:c.format,mainPost:c.post.body,postedAt:c.postedAt})}save();notice(a==='posted'?'投稿済みとして記録しました。':'投稿準備完了として保存しました。')}if(e.target.classList.contains('copy')){sync(id);let text=drafts[id][e.target.dataset.tcopy]||'';if(!text){notice('コピーする内容がありません。');return}navigator.clipboard?.writeText(text).then(()=>notice('コピーしました')).catch(()=>notice('コピーできませんでした'))}if(e.target.id==='export-btn'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='rakuten-travel-backup.json';a.click();$('backup-status').textContent='JSONを保存しました。'}});
document.addEventListener('input',e=>{if(e.target.dataset.t)drafts[e.target.dataset.id][e.target.dataset.t]=e.target.value;if(e.target.dataset.metric){let c=state.candidates.find(x=>x.id===e.target.dataset.id);c.metrics=c.metrics||{};c.metrics[e.target.dataset.metric]=e.target.value===''?null:Number(e.target.value);state.history=state.history.map(h=>h.candidateId===c.id?{...h,metrics:c.metrics}:h);localStorage.setItem(KEY,JSON.stringify(state));renderStats();renderAnalysis()}});
document.addEventListener('change',e=>{if(e.target.dataset.c){drafts[e.target.dataset.id][e.target.dataset.c]=e.target.value;compose(state.candidates.find(x=>x.id===e.target.dataset.id))}});
$('travel-form').addEventListener('submit',e=>{e.preventDefault();const now=new Date(),offset=now.getTimezoneOffset(),local=new Date(now.getTime()-offset*60000).toISOString().slice(0,16);$('checkedAt').value=local;let d=dataFromForm(),id=$('edit-id').value;if(!validHttpUrl(d.sourceUrl)||!validHttpUrl(d.affiliateUrl)||!validHttpUrl(d.threadsShortUrl)||!validHttpUrl(d.couponUrl)){notice('URLはhttp://またはhttps://で入力してください。');return}if(id)Object.assign(state.candidates.find(x=>x.id===id),d);else state.candidates.push({...d,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'draft',metrics:{}});save();clearForm();nav('candidates');notice('旅行情報を保存しました。')});
['new-btn','cancel-edit','candidate-new'].forEach(id=>$(id).addEventListener('click',()=>{clearForm();nav('travel')}));
$('travel-form').addEventListener('invalid',e=>{if(e.target.id==='facilityName')notice('施設紹介では施設名を入力してください。');},true);
$('import-file').addEventListener('change',e=>{let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d||!Array.isArray(d.candidates)||!Array.isArray(d.history)||!Array.isArray(d.sales)||typeof d.settings!=='object')throw Error();if(confirm('現在のデータを読み込んだデータで置き換えますか？')){state=d;save();$('backup-status').textContent='JSONを復元しました。'}}catch(x){$('backup-status').textContent='JSONを読み込めませんでした。既存データは変更していません。'}};r.readAsText(e.target.files[0])});
const RAKUTEN_SETTINGS_KEY='rakutenTravelPerformanceAssistantApiSettingsV1';
const RAKUTEN_ENDPOINT='https://openapi.rakuten.co.jp/engine/api/Travel/KeywordHotelSearch/20260731';
function loadRakutenSettings(){try{const value=JSON.parse(localStorage.getItem(RAKUTEN_SETTINGS_KEY)||'null');return value&&typeof value==='object'?value:{applicationId:'',accessKey:'',affiliateId:''}}catch{return {applicationId:'',accessKey:'',affiliateId:''}}}
let rakutenSettings=loadRakutenSettings();
function setupRakutenApiUI(){const backup=document.getElementById('backup'),travel=document.getElementById('travel');if(!backup||!travel)return;const settings=document.createElement('div');settings.className='panel';settings.innerHTML='<h3>楽天トラベルAPI設定</h3><p class="muted">認証情報はこのブラウザ内の専用設定へ保存します。Gitや公開ページのソースには保存しません。</p><div class="grid three"><label>Application ID<input id="rakuten-application-id" autocomplete="off"></label><label>Access Key<input id="rakuten-access-key" type="password" autocomplete="off"></label><label>Affiliate ID（任意）<input id="rakuten-affiliate-id" autocomplete="off"></label></div><div class="button-row"><button class="primary" type="button" id="rakuten-api-save">API設定を保存</button><button class="secondary" type="button" id="rakuten-api-clear">API設定をクリア</button></div><p id="rakuten-api-status" class="status" role="status" aria-live="polite"></p>';
backup.insertBefore(settings,backup.firstElementChild?.nextElementSibling||backup.firstChild);$('rakuten-application-id').value=rakutenSettings.applicationId||'';$('rakuten-access-key').value=rakutenSettings.accessKey||'';$('rakuten-affiliate-id').value=rakutenSettings.affiliateId||'';$('rakuten-api-save').addEventListener('click',()=>{rakutenSettings={applicationId:$('rakuten-application-id').value.trim(),accessKey:$('rakuten-access-key').value.trim(),affiliateId:$('rakuten-affiliate-id').value.trim()};localStorage.setItem(RAKUTEN_SETTINGS_KEY,JSON.stringify(rakutenSettings));$('rakuten-api-status').textContent='API設定を保存しました。'});$('rakuten-api-clear').addEventListener('click',()=>{rakutenSettings={applicationId:'',accessKey:'',affiliateId:''};localStorage.removeItem(RAKUTEN_SETTINGS_KEY);$('rakuten-application-id').value='';$('rakuten-access-key').value='';$('rakuten-affiliate-id').value='';$('rakuten-api-status').textContent='API設定をクリアしました。'});
const search=document.createElement('div');search.className='panel';search.innerHTML='<h3>楽天トラベルから検索</h3><p class="muted">施設名や地域で検索できます。取得料金は楽天APIの参考値です。</p><div class="button-row"><input id="rakuten-search-keyword" placeholder="例：ホテル日航福岡" aria-label="楽天トラベル検索キーワード"><button class="primary" type="button" id="rakuten-search-button">検索</button></div><p id="rakuten-search-status" class="status" role="status" aria-live="polite"></p><div id="rakuten-search-results" class="cards"></div>';
travel.insertBefore(search,travel.querySelector('form'));$('rakuten-search-button').addEventListener('click',searchRakutenHotels)}
function apiErrorMessage(body,status){const code=typeof body?.error==='string'?body.error:body?.error?.code;return code==='INVALID_KEYWORD'?'検索キーワードを確認してください。':code==='NO_RESULTS'?'検索結果がありません。':status===401||status===403?'楽天APIの認証または利用条件を確認してください。':'楽天APIから情報を取得できませんでした。'}
async function searchRakutenHotels(){const status=$('rakuten-search-status'),results=$('rakuten-search-results'),keyword=$('rakuten-search-keyword').value.trim();if(!rakutenSettings.applicationId||!rakutenSettings.accessKey){status.textContent='先にバックアップ・設定で楽天API設定を保存してください。';return}if(keyword.length<2||keyword.length>50){status.textContent='検索キーワードは2〜50文字で入力してください。';return}status.textContent='検索中...';results.innerHTML='';const params=new URLSearchParams({applicationId:rakutenSettings.applicationId,accessKey:rakutenSettings.accessKey,keyword,format:'json'});if(rakutenSettings.affiliateId)params.set('affiliateId',rakutenSettings.affiliateId);try{const response=await fetch(`${RAKUTEN_ENDPOINT}?${params}`),body=await response.json();if(!response.ok){status.textContent=apiErrorMessage(body,response.status);return}const hotels=Array.isArray(body?.hotels)?body.hotels:[],items=hotels.map(entry=>{const basic=entry?.hotel?.[0]?.hotelBasicInfo;return basic&&typeof basic==='object'?basic:null}).filter(Boolean).slice(0,10);if(!items.length){status.textContent='検索結果がありません。';return}status.textContent=`${items.length}件見つかりました。`;results.innerHTML=items.map((hotel,index)=>'<article class="card"><h3>'+esc(hotel.hotelName||'施設名未取得')+'</h3><p>'+esc([hotel.address1,hotel.address2].filter(Boolean).join(' '))+'</p><p>'+esc(hotel.hotelSpecial||'')+'</p><p><strong>楽天API参考料金：</strong>'+fmt(hotel.hotelMinCharge)+'円</p><p class="muted">取得時点の最安値の目安です。予約時の料金を保証するものではありません。</p><button class="primary" type="button" data-rakuten-index="'+index+'">この施設を使う</button></article>').join('');results.querySelectorAll('[data-rakuten-index]').forEach(button=>button.addEventListener('click',()=>applyRakutenHotel(items[Number(button.dataset.rakutenIndex)])))}catch(error){status.textContent=error instanceof TypeError?'ブラウザから楽天APIへ接続できませんでした。':'楽天APIから情報を取得できませんでした。'}}
function applyRakutenHotel(hotel){const hasInput=$('facilityName').value.trim()||$('attraction').value.trim()||$('sourceUrl').value.trim();if(hasInput&&!confirm('入力済みの内容があります。楽天トラベル情報で置き換えますか？'))return;currentRakutenSelection=hotel;$('postCategory').value='hotel';$('facilityName').value=hotel.hotelName||'';$('region').value=[hotel.address1,hotel.address2].filter(Boolean).join(' ')||'';$('attraction').value=hotel.hotelSpecial||'';$('sourceUrl').value=hotel.hotelInformationUrl||'';$('affiliateUrl').value=hotel.hotelInformationUrl||'';$('threadsShortUrl').value='';['campaignName','campaignRegion','discountText','startAt','endAt','firstComeCondition','campaignConditionsNew','campaignNotes','dealDiscountRate','dealDiscountAmount','dealText','dealDeadline','dealConditions','couponUrl'].forEach(id=>{if($(id))$(id).value=''});if($('isFirstCome'))$('isFirstCome').checked=false;$('currentPrice').value='';$('regularPrice').value='';$('discountAmount').value='';$('discountRate').value='';$('verificationStatus').value='unverified';$('postCategory').dispatchEvent(new Event('change'));nav('travel');notice('楽天トラベル情報をフォームへ反映しました。お得情報と短縮URLを確認して保存してください。')}
const originalDataFromForm=dataFromForm;dataFromForm=function(){const data=originalDataFromForm();if(currentRakutenSelection){data.sourceType='rakuten_travel_api';data.rakutenHotelNo=currentRakutenSelection.hotelNo||null;data.rakutenFetchedAt=new Date().toISOString();data.rakutenDataVersion='2026-07-31';data.rakutenSourceUrl=currentRakutenSelection.hotelInformationUrl||null;data.rakutenReferenceMinCharge=currentRakutenSelection.hotelMinCharge??null;data.rakutenReferenceMinChargeFetchedAt=data.rakutenFetchedAt}return data};
function setupShortUrlUI(){const source=$('sourceUrl'),field=source?.closest('fieldset');if(!field||$('threadsShortUrl'))return;const label=document.createElement('label');label.innerHTML='Threads用短縮URL<input id="threadsShortUrl" type="url" placeholder="https://a.r10.to/..." autocomplete="off"><span class="small">楽天公式で作成した短縮アフィリエイトURLを貼り付けてください。楽天以外の短縮サービスは使用しません。</span></label>';field.querySelector('.grid')?.appendChild(label)}
function setupDealUI(){const form=$('travel-form'),oldField=form?.querySelectorAll('fieldset')[2];if(!form||!oldField||$('deal-panel'))return;oldField.hidden=true;const panel=document.createElement('fieldset');panel.id='deal-panel';panel.innerHTML='<legend>お得情報</legend><div class="button-row"><a class="secondary" href="https://travel.rakuten.co.jp/coupon/yado/?l-id=top_subnavi_yadocoupon" target="_blank" rel="noopener noreferrer">楽天公式で宿クーポンを探す</a></div><div class="grid three"><div><strong>お得タイプ</strong><label><span><input type="radio" name="dealType" value="discountRate" checked> 割引率</span></label><label><span><input type="radio" name="dealType" value="discountAmount"> 割引額</span></label><label><span><input type="radio" name="dealType" value="other"> その他</span></label></div><label id="deal-rate-wrap">割引率<input id="dealDiscountRate" type="number" min="0" max="100" placeholder="50"> %</label><label id="deal-amount-wrap" hidden>割引額<input id="dealDiscountAmount" type="number" min="0" placeholder="5000"> 円OFF</label><label id="deal-text-wrap" hidden>その他お得情報<input id="dealText" placeholder="子ども料金半額"></label><label>期限<input id="dealDeadline" type="date"></label><label>条件・ひとこと<textarea id="dealConditions" rows="2" placeholder="対象プラン限定、先着100枚など"></textarea></label><label>楽天公式クーポンURL<input id="couponUrl" type="url" placeholder="https://"></label></div><p class="muted">割引率・割引額は楽天公式ページで確認した内容だけ入力してください。情報確認日時は保存時に自動記録します。</p><p id="deal-checked-at" class="status"></p>';
oldField.parentNode.insertBefore(panel,oldField);const update=()=>{const type=form.querySelector('input[name="dealType"]:checked')?.value||'discountRate';$('deal-rate-wrap').hidden=type!=='discountRate';$('deal-amount-wrap').hidden=type!=='discountAmount';$('deal-text-wrap').hidden=type!=='other'};form.querySelectorAll('input[name="dealType"]').forEach(input=>input.addEventListener('change',update));update();}
function setupPostCategoryUI(){const form=$('travel-form'),firstField=form?.querySelector('fieldset');if(!form||!firstField||$('postCategory'))return;const panel=document.createElement('div');panel.className='panel';panel.innerHTML='<label>投稿タイプ<select id="postCategory"><option value="hotel">施設紹介</option><option value="campaign">キャンペーン／クーポン</option></select></label><p id="campaign-mode-note" class="muted"></p>';form.insertBefore(panel,firstField);const update=()=>{const campaign=$('postCategory').value==='campaign';form.querySelectorAll('fieldset')[0].hidden=campaign;form.querySelectorAll('fieldset')[1].hidden=campaign;$('deal-panel').hidden=campaign;$('facilityName').required=!campaign;$('campaign-mode-note').textContent=campaign?'キャンペーン名・地域・割引内容・開始日時・先着条件を入力してください。':'ホテル情報とお得情報を入力してください。';const urlField=form.querySelectorAll('fieldset')[3];urlField.querySelectorAll('label').forEach(label=>{const text=label.textContent||'';if(text.includes('アフィリエイトURL')||text.includes('宿泊経験'))label.hidden=campaign})};$('postCategory').addEventListener('change',update);update()}
function setupCampaignUI(){const form=$('travel-form'),urlField=form?.querySelectorAll('fieldset')[3];if(!form||!urlField||$('campaign-panel'))return;const panel=document.createElement('fieldset');panel.id='campaign-panel';panel.innerHTML='<legend>キャンペーン／クーポン情報</legend><div class="grid two"><label>キャンペーン名<input id="campaignName" placeholder="九州ふっこう応援割｜佐賀"></label><label>対象地域<input id="campaignRegion" placeholder="佐賀県"></label><label>割引内容<input id="discountText" placeholder="国内宿泊 50%OFF"></label><label>利用開始日時<input id="startAt" type="datetime-local" placeholder="未確認"><span class="small">未確認の場合は空欄です</span></label><label>終了日時（任意）<input id="endAt" type="datetime-local" placeholder="未確認"><span class="small">未確認の場合は空欄です</span></label><label><span><input id="isFirstCome" type="checkbox"> 先着順</span></label><label>先着条件<input id="firstComeCondition" placeholder="予約完了した先着順"></label><label>対象施設・利用条件<input id="campaignConditionsNew" placeholder="対象施設・利用条件あり"></label><label>注意事項<textarea id="campaignNotes" rows="2"></textarea></label></div>';urlField.parentNode.insertBefore(panel,urlField);const update=()=>{const disabled=$('postCategory').value!=='campaign';panel.hidden=disabled};$('postCategory').addEventListener('change',update);update()}
document.addEventListener('click',e=>{if((e.target.dataset.a==='ready'||e.target.dataset.a==='posted')&&$('postCategory')?.value==='campaign'&&!$('threadsShortUrl')?.value.trim()){e.preventDefault();e.stopImmediatePropagation();notice('キャンペーン投稿にはThreads用短縮URLを入力してください。') }},true);
function setupUrlCopyButtons(){[['sourceUrl','情報元URLをコピー'],['affiliateUrl','アフィリエイトURLをコピー'],['threadsShortUrl','短縮URLをコピー']].forEach(([id,label])=>{const input=$(id);if(!input||$(id+'-copy'))return;const button=document.createElement('button');button.type='button';button.id=id+'-copy';button.className='secondary';button.textContent=label;input.insertAdjacentElement('afterend',button);button.addEventListener('click',()=>{const value=input.value.trim();if(value)copyTextWithFeedback(value,{button,label})})})}
const originalCompose=compose;compose=function(candidate){originalCompose(candidate);if(candidate.affiliateUrl&&!candidate.threadsShortUrl){const target=$('compose-'+candidate.id);if(target){const warning=document.createElement('div');warning.className='warning';warning.textContent='Threads用短縮URLを入力してください。長いアフィリエイトURLは投稿文へ自動使用しません。';target.querySelector('.panel')?.prepend(warning)}}};
document.addEventListener('click',e=>{if(e.target.dataset.a==='edit'){setTimeout(()=>{const candidate=state.candidates.find(x=>x.id===$('edit-id').value);if(!candidate)return;const type=candidate.dealType||'discountRate';const radio=$('deal-panel')?.querySelector('input[name="dealType"][value="'+type+'"]');if(radio)radio.checked=true;if($('dealDiscountRate'))$('dealDiscountRate').value=candidate.discountRate??'';if($('dealDiscountAmount'))$('dealDiscountAmount').value=candidate.discountAmount??'';if($('dealText'))$('dealText').value=candidate.dealText??'';if($('dealDeadline'))$('dealDeadline').value=candidate.dealDeadline??'';if($('dealConditions'))$('dealConditions').value=candidate.dealConditions??'';if($('couponUrl'))$('couponUrl').value=candidate.couponUrl??'';$('deal-panel')?.querySelector('input[name="dealType"]:checked')?.dispatchEvent(new Event('change'))},0)}});
setupRakutenApiUI();setupShortUrlUI();setupUrlCopyButtons();setupDealUI();setupPostCategoryUI();setupCampaignUI();nav('dashboard');render();
document.addEventListener('click',e=>{if(e.target.dataset.a==='edit'){setTimeout(()=>{const candidate=state.candidates.find(x=>x.id===$('edit-id').value);if(!candidate)return;$('postCategory').value=candidate.postCategory||'hotel';$('postCategory').dispatchEvent(new Event('change'));['campaignName','campaignRegion','discountText','startAt','endAt','firstComeCondition','campaignConditionsNew','campaignNotes'].forEach(id=>{if($(id))$(id).value=candidate[id]??''});if($('isFirstCome'))$('isFirstCome').checked=Boolean(candidate.isFirstCome)},0)}});

const SALE_STATUS_LABEL={confirmed:'🟢 確認済み',conditional:'🟡 条件あり',review:'🔴 要確認'};
function renderSales(){const box=$('sale-list');if(!box)return;if(!state.sales.length){box.innerHTML='<div class="empty">楽天公式で確認したセール・クーポンを登録すると、ここに表示されます。</div>';return}box.innerHTML=state.sales.map(s=>'<article class="card"><h3>🔥 '+esc(s.name)+'</h3><div class="card-meta"><span>'+esc(s.region||'対象地域未入力')+'</span><span class="badge">'+SALE_STATUS_LABEL[s.confirmStatus]+'</span><span class="badge">'+('🔥'.repeat(Number(s.value)||1))+'</span></div><p><strong>割引内容：</strong>'+esc(s.discountText||'未確認')+'</p><p><strong>予約期間：</strong>'+esc(s.bookingPeriod||'未確認')+'<br><strong>旅行対象期間：</strong>'+esc(s.travelPeriod||'未確認')+'</p><p><strong>条件：</strong>'+esc(s.conditions||'公式ページで確認してください。')+'</p><p class="muted">公式確認：'+esc(s.checkedAtDisplay||'未記録')+'</p><div class="card-actions"><a class="secondary" href="'+esc(s.sourceUrl)+'" target="_blank" rel="noopener noreferrer">楽天公式を確認</a><button class="primary" type="button" data-sale-action="use" data-sale-id="'+esc(s.id)+'">キャンペーン投稿に使う</button><button class="danger" type="button" data-sale-action="delete" data-sale-id="'+esc(s.id)+'">削除</button></div></article>').join('')}
function clearSaleForm(){$('deal-discovery-form')?.reset();if($('sale-status'))$('sale-status').value='confirmed';if($('sale-value'))$('sale-value').value='3';if($('sale-checked-at')){$('sale-checked-at').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}}
function useSale(s){$('postCategory').value='campaign';$('postCategory').dispatchEvent(new Event('change'));const values={campaignName:s.name,campaignRegion:s.region,discountText:s.discountText,startAt:'',endAt:'',firstComeCondition:'',campaignConditionsNew:s.conditions,campaignNotes:[s.bookingPeriod?'予約期間：'+s.bookingPeriod:'',s.travelPeriod?'旅行対象期間：'+s.travelPeriod:'',s.notes].filter(Boolean).join('\n'),sourceUrl:s.sourceUrl,campaignPeriod:s.travelPeriod,checkedAt:s.checkedAt,verificationStatus:s.confirmStatus==='confirmed'?'verified':'recheck'};Object.entries(values).forEach(([id,value])=>{if($(id))$(id).value=value||''});nav('travel');notice('セール情報をキャンペーン投稿欄へ反映しました。内容を確認して保存してください。')}
const baseRender=render;render=function(){baseRender();renderSales()};renderSales();clearSaleForm();
$('deal-discovery-form')?.addEventListener('submit',e=>{e.preventDefault();const sourceUrl=$('sale-source-url').value.trim();if(!validHttpUrl(sourceUrl)){notice('公式URLはhttp://またはhttps://で入力してください。');return}const checkedAt=$('sale-checked-at').value||new Date().toISOString();const record={id:crypto.randomUUID(),name:$('sale-name').value.trim(),region:$('sale-region').value.trim(),discountText:$('sale-discount').value.trim(),sourceUrl,bookingPeriod:$('sale-booking-period').value.trim(),travelPeriod:$('sale-travel-period').value.trim(),conditions:$('sale-conditions').value.trim(),notes:$('sale-notes').value.trim(),confirmStatus:$('sale-status').value,value:Number($('sale-value').value)||3,checkedAt,checkedAtDisplay:new Date(checkedAt).toLocaleString('ja-JP')};const duplicate=state.sales.find(s=>s.sourceUrl===record.sourceUrl&&s.name===record.name);if(duplicate)Object.assign(duplicate,record,{id:duplicate.id});else state.sales.push(record);save();clearSaleForm();$('deal-discovery-status').textContent=duplicate?'既存のセール情報を更新しました。':'セール情報を保存しました。'});
$('deal-discovery-clear')?.addEventListener('click',clearSaleForm);
document.addEventListener('click',e=>{const action=e.target.dataset.saleAction;if(!action)return;const sale=state.sales.find(s=>s.id===e.target.dataset.saleId);if(!sale)return;if(action==='use')useSale(sale);if(action==='delete'&&confirm('このセール情報を削除しますか？')){state.sales=state.sales.filter(s=>s.id!==sale.id);save()}});

function saleDateParts(text){return String(text||'').match(/(20\d{2})[\/\-年](\d{1,2})[\/\-月](\d{1,2})/g)||[]}
function saleIsActive(s){const parts=saleDateParts(s.bookingPeriod);if(parts.length<2)return false;const parse=v=>new Date(v.replace('年','/').replace('月','/').replace('日',''));const dates=parts.map(parse).filter(v=>!Number.isNaN(v.getTime()));return dates.length>=2&&dates[0]<=new Date()&&new Date()<=dates[dates.length-1]}
function filteredSales(){const keyword=($('saved-sale-keyword')?.value||'').trim().toLowerCase(),region=($('saved-sale-region')?.value||'').trim().toLowerCase(),status=$('saved-sale-status')?.value||'all';return state.sales.filter(s=>{const hay=[s.name,s.discountText,s.conditions,s.notes].join(' ').toLowerCase();return(!keyword||hay.includes(keyword))&&(!region||String(s.region||'').toLowerCase().includes(region))&&(status==='all'||status===s.confirmStatus||(status==='active'&&saleIsActive(s)))})}
const saleListRender=renderSales;renderSales=function(){const list=filteredSales();if(!list.length){const box=$('sale-list');if(box)box.innerHTML='<div class="empty">条件に一致する保存済みセールはありません。</div>';return}const box=$('sale-list');if(!box)return;box.innerHTML=list.map(s=>'<article class="card"><h3>🔥 '+esc(s.name)+'</h3><div class="card-meta"><span>'+esc(s.region||'対象地域未入力')+'</span><span class="badge">'+SALE_STATUS_LABEL[s.confirmStatus]+'</span><span class="badge">'+('🔥'.repeat(Number(s.value)||1))+'</span></div><p><strong>割引内容：</strong>'+esc(s.discountText||'未確認')+'</p><p><strong>予約期間：</strong>'+esc(s.bookingPeriod||'未確認')+'<br><strong>旅行対象期間：</strong>'+esc(s.travelPeriod||'未確認')+'</p><p><strong>条件：</strong>'+esc(s.conditions||'公式ページで確認してください。')+'</p><p class="muted">公式確認：'+esc(s.checkedAtDisplay||'未記録')+'</p><div class="card-actions"><a class="secondary" href="'+esc(s.sourceUrl)+'" target="_blank" rel="noopener noreferrer">楽天公式を確認</a><button class="primary" type="button" data-sale-action="use" data-sale-id="'+esc(s.id)+'">キャンペーン投稿に使う</button><button class="danger" type="button" data-sale-action="delete" data-sale-id="'+esc(s.id)+'">削除</button></div></article>').join('')};
function setupSaleSearchUI(){const deals=$('deals'),anchor=deals?.querySelector('#deal-discovery-form')?.closest('.panel');if(!deals||!anchor||$('official-sale-search'))return;const panel=document.createElement('div');panel.className='panel';panel.innerHTML='<h3>楽天公式から探す</h3><p class="muted">楽天公式のクーポン検索ページを開きます。公式ページで内容を確認したあと、登録欄へ入力してください。</p><div class="grid three"><label>キーワード<input id="official-sale-keyword" placeholder="例：50%OFF、佐賀"></label><label>地域<select id="official-sale-region"><option value="all">全国</option><option value="kyushu">九州</option></select></label><label>状態<select id="official-sale-status"><option value="active">開催中</option><option value="upcoming">開催予定</option><option value="ending">終了間近</option></select></label></div><div class="button-row"><button class="primary" type="button" id="official-sale-search">楽天公式から検索</button><button class="secondary" type="button" data-official-quick="new">新着を探す</button><button class="secondary" type="button" data-official-quick="kyushu">九州を探す</button><button class="secondary" type="button" data-official-quick="ending">終了間近を探す</button></div><p id="official-sale-status-message" class="status" role="status" aria-live="polite"></p><hr><h3>保存済みセールを探す</h3><div class="grid three"><label>キーワード<input id="saved-sale-keyword" placeholder="名称・割引・条件"></label><label>地域<input id="saved-sale-region" placeholder="例：佐賀県"></label><label>状態<select id="saved-sale-status"><option value="all">すべて</option><option value="confirmed">確認済み</option><option value="conditional">条件あり</option><option value="review">要確認</option><option value="active">開催中（入力期間内）</option></select></label></div><p class="muted">入力すると保存済みのセール候補を絞り込みます。</p>';deals.insertBefore(panel,anchor);const openOfficial=(mode='search')=>{const region=$('official-sale-region')?.value||'all',url=region==='kyushu'?'https://coupon.travel.rakuten.co.jp/coupon/search/japan_12-0-0-0-2-1':'https://coupon.travel.rakuten.co.jp/coupon/';window.open(url,'_blank','noopener,noreferrer');const q=$('official-sale-keyword')?.value.trim();const state=$('official-sale-status')?.value||'active';$('official-sale-status-message').textContent=(q?'キーワード「'+q+'」を公式ページで確認してください。':'公式ページで検索条件を指定してください。')+' 地域：'+(region==='kyushu'?'九州':'全国')+'／状態：'+state+'。'};$('official-sale-search').addEventListener('click',()=>openOfficial('search'));document.querySelectorAll('[data-official-quick]').forEach(button=>button.addEventListener('click',()=>{const mode=button.dataset.officialQuick;if(mode==='kyushu')$('official-sale-region').value='kyushu';if(mode==='new')$('official-sale-status').value='active';if(mode==='ending')$('official-sale-status').value='ending';openOfficial(mode)}));['saved-sale-keyword','saved-sale-region','saved-sale-status'].forEach(id=>$(id).addEventListener('input',()=>renderSales()))}
setupSaleSearchUI();renderSales();

let pendingChatGptImport=null,currentChatGptImport=null;
function firstValue(value){return Array.isArray(value)?value.filter(Boolean).join('、'):value??''}
function extractChatGptJson(text){const source=String(text||'').trim();const fenced=source.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);return JSON.parse(fenced?fenced[1]:source)}
function normalizedChatGptImport(data){
  if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('JSONの最上位はオブジェクトにしてください。');
  const hotel=data.hotel&&typeof data.hotel==='object'&&!Array.isArray(data.hotel)?data.hotel:{};
  const campaign=data.campaign&&typeof data.campaign==='object'&&!Array.isArray(data.campaign)?data.campaign:{};
  const plan=data.plan&&typeof data.plan==='object'&&!Array.isArray(data.plan)?data.plan:{};
  const sources=Array.isArray(data.sources)?data.sources.filter(s=>s&&typeof s==='object').map(s=>({url:String(s.url||''),name:String(s.name||''),sourceType:String(s.sourceType||''),supports:Array.isArray(s.supports)?s.supports.map(String):[]})):[];
  const facts={hotel:{name:String(hotel.name||''),area:String(hotel.area||''),address:hotel.address??null,rakutenUrl:String(hotel.rakutenUrl||''),features:Array.isArray(hotel.features)?hotel.features.map(String):[],facilities:Array.isArray(hotel.facilities)?hotel.facilities.map(String):[],meal:hotel.meal??null,onsen:hotel.onsen??null},campaign:{name:campaign.name??null,discount:campaign.discount??null,bookingStart:campaign.bookingStart??null,bookingEnd:campaign.bookingEnd??null,stayStart:campaign.stayStart??null,stayEnd:campaign.stayEnd??null,areas:Array.isArray(campaign.areas)?campaign.areas.map(String):[],conditions:Array.isArray(campaign.conditions)?campaign.conditions.map(String):[]},plan:{name:plan.name??null,price:plan.price??null,priceCondition:plan.priceCondition??null},sources,checkedAt:String(data.checkedAt||''),notes:Array.isArray(data.notes)?data.notes.map(String):[]};
  return facts;
}
function displayFact(value){if(value===null||value===undefined||value==='')return '未確認';return Array.isArray(value)?(value.length?value.map(esc).join('、'):'未確認'):esc(String(value))}
function renderChatGptPreview(f){const campaignName=f.campaign.name||'';const hotelName=f.hotel.name||'';const sourceLinks=f.sources.filter(s=>validHttpUrl(s.url)).map(s=>'<li><a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.name||s.url)+'</a></li>').join('');$('chatgpt-import-preview').innerHTML='<div class="panel import-preview"><h3>調査結果（FACT確認）</h3><div class="grid two"><div><h4>宿泊施設</h4><p>'+displayFact(hotelName)+'</p><h4>地域</h4><p>'+displayFact(f.hotel.area)+'</p><h4>住所</h4><p>'+displayFact(f.hotel.address)+'</p><h4>特徴</h4><p>'+displayFact(f.hotel.features)+'</p><h4>温泉</h4><p>'+displayFact(f.hotel.onsen)+'</p><h4>食事</h4><p>'+displayFact(f.hotel.meal)+'</p></div><div><h4>キャンペーン</h4><p>'+displayFact(campaignName)+'</p><h4>割引</h4><p>'+displayFact(f.campaign.discount)+'</p><h4>予約期限</h4><p>'+displayFact([f.campaign.bookingStart,f.campaign.bookingEnd].filter(Boolean).join('〜'))+'</p><h4>宿泊対象期間</h4><p>'+displayFact([f.campaign.stayStart,f.campaign.stayEnd].filter(Boolean).join('〜'))+'</p><h4>対象地域</h4><p>'+displayFact(f.campaign.areas)+'</p><h4>条件</h4><p>'+displayFact(f.campaign.conditions)+'</p></div></div><p><strong>情報確認日：</strong>'+displayFact(f.checkedAt)+'</p><p><strong>情報源：</strong></p><ul>'+(sourceLinks||'<li>未確認</li>')+'</ul><p class="warning">ChatGPTの出力だけでは楽天公式確認済みとは判定しません。リンク先を人間が確認してから反映してください。</p><div class="button-row"><button class="primary" type="button" id="chatgpt-import-use">この内容を使う</button></div></div>'}
function setDateTimeField(id,value){if(!$(id))return;const match=String(value||'').match(/(\d{4})[\/\-年](\d{1,2})[\/\-月](\d{1,2})(?:[ T](\d{1,2}):?(\d{2})?)?/);$(id).value=match?match[1]+'-'+String(match[2]).padStart(2,'0')+'-'+String(match[3]).padStart(2,'0')+(match[4]?'T'+String(match[4]).padStart(2,'0')+':'+String(match[5]||'00').padStart(2,'0'):''):''}
function setChatGptBookingFields(campaign){
  const booking=campaign&&typeof campaign==='object'?campaign:{};
  setDateTimeField('startAt',booking.bookingStart==null?'':booking.bookingStart);
  setDateTimeField('endAt',booking.bookingEnd==null?'':booking.bookingEnd);
}
function useChatGptImport(f){if(!f)return;pendingChatGptImport=f;currentChatGptImport=f;const hasCampaign=Boolean(f.campaign.name||f.campaign.discount||f.campaign.bookingStart||f.campaign.bookingEnd||f.campaign.conditions.length);$('postCategory').value=hasCampaign?'campaign':'hotel';$('postCategory').dispatchEvent(new Event('change'));const source=f.sources.find(s=>validHttpUrl(s.url))?.url||f.hotel.rakutenUrl||'';if(hasCampaign){const values={campaignName:f.campaign.name||'',campaignRegion:firstValue(f.campaign.areas),discountText:f.campaign.discount||'',startAt:f.campaign.bookingStart||'',endAt:f.campaign.bookingEnd||'',campaignConditionsNew:firstValue(f.campaign.conditions),campaignNotes:[...f.notes,[f.campaign.stayStart,f.campaign.stayEnd].filter(Boolean).join('〜')].filter(Boolean).join('\n'),sourceUrl:source,checkedAt:f.checkedAt,verificationStatus:'recheck',campaignPeriod:[f.campaign.stayStart,f.campaign.stayEnd].filter(Boolean).join('〜')};Object.entries(values).forEach(([id,value])=>{if($(id))$(id).value=value||''})}else{$('facilityName').value=f.hotel.name;$('region').value=f.hotel.area;$('attraction').value=[...f.hotel.features,...f.hotel.facilities,f.hotel.onsen?'温泉：'+f.hotel.onsen:'',f.hotel.meal?'食事：'+f.hotel.meal:''].filter(Boolean).join('、');$('sourceUrl').value=source;$('stayConditions').value=firstValue(f.campaign.conditions);$('notes').value=f.notes.join('\n')}nav('travel');notice('調査結果を既存フォームへ反映しました。内容を確認・修正して保存してください。')}
function setupChatGptImportUI(){const deals=$('deals'),anchor=deals?.querySelector('#deal-discovery-form')?.closest('.panel');if(!deals||!anchor||$('chatgpt-import-input'))return;const panel=document.createElement('div');panel.className='panel';panel.innerHTML='<h3>ChatGPT調査結果を取り込む</h3><p class="muted">ChatGPTで確認した構造化JSONを貼り付け、内容を確認してから既存フォームへ反映します。解析しただけでは保存されません。</p><textarea id="chatgpt-import-input" rows="10" placeholder="ChatGPTの調査結果JSONをここに貼り付け"></textarea><div class="button-row"><button class="primary" type="button" id="chatgpt-import-parse">解析する</button><button class="secondary" type="button" id="chatgpt-import-clear">クリア</button></div><p id="chatgpt-import-status" class="status" role="status" aria-live="polite"></p><div id="chatgpt-import-preview"></div>';deals.insertBefore(panel,anchor);$('chatgpt-import-parse').addEventListener('click',()=>{try{const facts=normalizedChatGptImport(extractChatGptJson($('chatgpt-import-input').value));pendingChatGptImport=facts;renderChatGptPreview(facts);$('chatgpt-import-status').textContent='解析しました。FACTを確認してください。'}catch(error){pendingChatGptImport=null;$('chatgpt-import-preview').innerHTML='';$('chatgpt-import-status').textContent='解析できませんでした。JSON形式と必須のオブジェクト構造を確認してください。'+(error.message?' '+error.message:'')}});$('chatgpt-import-clear').addEventListener('click',()=>{$('chatgpt-import-input').value='';$('chatgpt-import-preview').innerHTML='';$('chatgpt-import-status').textContent='';pendingChatGptImport=null})}
document.addEventListener('click',e=>{if(e.target.id==='chatgpt-import-use')useChatGptImport(pendingChatGptImport)})
document.addEventListener('click',e=>{if(['new-btn','cancel-edit','candidate-new'].includes(e.target.id))currentChatGptImport=null})
const originalImportedDataFromForm=dataFromForm;dataFromForm=function(){const data=originalImportedDataFromForm();if(currentChatGptImport)data.chatgptResearchFacts=currentChatGptImport;return data};
const originalUseChatGptImport=useChatGptImport;useChatGptImport=function(f){originalUseChatGptImport(f);if(f?.campaign)setChatGptBookingFields(f.campaign)};
setupChatGptImportUI();

const CHATGPT_JSON_TEMPLATE={hotel:{name:'',area:'',address:null,rakutenUrl:'',features:[],facilities:[],meal:null,onsen:null},campaign:{name:null,discount:null,bookingStart:null,bookingEnd:null,stayStart:null,stayEnd:null,areas:[],conditions:[]},plan:{name:null,price:null,priceCondition:null},sources:[],checkedAt:'',notes:[]};
const RESEARCH_OPTIONS={purpose:[['sale_campaign','セール・クーポン'],['deal_hotel','お得な宿'],['sale_and_hotel','セール＋対象宿'],['travel_topic','旅行ネタ']],travelType:[['hotel_only','ホテル・旅館のみ'],['hotel_flight','ホテル＋飛行機'],['hotel_jr','ホテル＋JR'],['rental_car','レンタカー'],['unspecified','指定なし']],discount:[['50','50%以上'],['40','40%以上'],['30','30%以上'],['20','20%以上'],['10','10%以上'],['none','割引率指定なし'],['amount','金額割引を探す']],region:[['all','全国'],['kyushu','九州'],['fukuoka','福岡県'],['saga','佐賀県'],['nagasaki','長崎県'],['kumamoto','熊本県'],['oita','大分県'],['miyazaki','宮崎県'],['kagoshima','鹿児島県'],['custom','自由入力']],period:[['available','現在予約可能'],['week','今週'],['month','今月'],['next_month','来月'],['date','日付指定'],['none','指定なし']],count:[['3','3件'],['5','5件'],['10','10件']]};
const RESEARCH_PRIORITIES=[['discount','割引率'],['new','新着'],['ending','終了間近'],['onsen','温泉'],['meal','食事'],['luxury','高級宿'],['family','家族旅行'],['solo','一人旅']];
function optionMarkup(items,selected){return items.map(([value,label])=>'<option value="'+value+'" '+(value===selected?'selected':'')+'>'+label+'</option>').join('')}
function selectedLabel(id,options){const value=$(id)?.value;return options.find(x=>x[0]===value)?.[1]||'指定なし'}
function buildResearchPrompt(){const purpose=selectedLabel('research-purpose',RESEARCH_OPTIONS.purpose),travel=selectedLabel('research-travel-type',RESEARCH_OPTIONS.travelType),discount=selectedLabel('research-discount',RESEARCH_OPTIONS.discount),regionValue=$('research-region')?.value||'all',region=regionValue==='custom'?($('research-custom-region')?.value.trim()||'自由入力（未指定）'):selectedLabel('research-region',RESEARCH_OPTIONS.region),period=selectedLabel('research-period',RESEARCH_OPTIONS.period),count=selectedLabel('research-count',RESEARCH_OPTIONS.count),priorities=RESEARCH_PRIORITIES.filter(([value])=>$('research-priority-'+value)?.checked).map(([,label])=>label),dateText=period==='日付指定'?[ $('research-date-start')?.value,$('research-date-end')?.value].filter(Boolean).join('〜')||'未指定':'';
  const discountRule=discount==='割引率指定なし'?'割引率の指定はありません。':discount==='金額割引を探す'?'金額割引を探してください。':discount+'の条件を満たす情報だけを探してください。';
  return ['楽天トラベルで現在利用できる旅行情報をWeb調査してください。','【検索条件】','目的：'+purpose,'旅行タイプ：'+travel,'割引条件：'+discount+(dateText?'\n日付指定：'+dateText:''),'地域：'+region,'予約・旅行条件：'+period,'取得件数：'+count,'重視する条件：'+(priorities.join('、')||'指定なし'),'【調査ルール】','楽天トラベル公式情報を最優先してください。','予約期間と宿泊・旅行対象期間は別々に確認してください。','キャンペーン名、割引内容、予約期間、宿泊対象期間、対象地域、対象サービス、利用条件、除外条件を確認してください。',travel==='ホテル・旅館のみ'?'ホテル・旅館のみを対象とし、航空券付きパック、JR付き商品、レンタカー商品を検索結果へ混ぜないでください。':'選択した旅行タイプ以外の商品を検索結果へ混ぜないでください。',discountRule,'条件を満たす情報が確認できない場合、条件を勝手に緩和せず「該当なし」としてください。','確認できない情報は推測せずnullまたは空配列にしてください。','「最大50%OFF」など条件付きの表記は、すべての利用者・施設に適用されるものとして扱わず、適用条件を確認してください。','各FACTの確認に利用した情報源URLをsourcesへ保持してください。','最後に、楽天トラベル Threads投稿アシスタントへ取り込める指定JSON形式で出力してください。','【指定JSON形式】',JSON.stringify(CHATGPT_JSON_TEMPLATE,null,2)].join('\n')}
function setupTravelResearchUI(){const deals=$('deals'),importPanel=$('chatgpt-import-input')?.closest('.panel');if(!deals||!importPanel||$('ai-travel-research-panel'))return;const panel=document.createElement('div');panel.id='ai-travel-research-panel';panel.className='panel';panel.innerHTML='<h3>AI旅行ネタ調査</h3><p class="muted">条件を選んでChatGPT用プロンプトを作成します。調査と事実確認はChatGPT・人間が行い、結果は下の既存取り込み欄で解析します。</p><div class="grid three"><label>探したいもの<select id="research-purpose">'+optionMarkup(RESEARCH_OPTIONS.purpose,'sale_and_hotel')+'</select></label><label>旅行タイプ<select id="research-travel-type">'+optionMarkup(RESEARCH_OPTIONS.travelType,'hotel_only')+'</select></label><label>割引条件<select id="research-discount">'+optionMarkup(RESEARCH_OPTIONS.discount,'20')+'</select></label><label>地域<select id="research-region">'+optionMarkup(RESEARCH_OPTIONS.region,'all')+'</select></label><label>予約・旅行期間<select id="research-period">'+optionMarkup(RESEARCH_OPTIONS.period,'available')+'</select></label><label>取得件数<select id="research-count">'+optionMarkup(RESEARCH_OPTIONS.count,'5')+'</select></label></div><div id="research-custom-region-wrap" hidden><label>地域（自由入力）<input id="research-custom-region" placeholder="例：長崎県・雲仙"></label></div><div id="research-date-wrap" class="grid two" hidden><label>開始日<input id="research-date-start" type="date"></label><label>終了日<input id="research-date-end" type="date"></label></div><fieldset><legend>重視する条件（複数選択）</legend><div class="grid four">'+RESEARCH_PRIORITIES.map(([value,label])=>'<label><span><input type="checkbox" id="research-priority-'+value+'"> '+label+'</span></label>').join('')+'</div></fieldset><div class="button-row"><button class="primary" type="button" id="research-prompt-generate">ChatGPT用プロンプトを作成</button><button class="secondary" type="button" id="research-prompt-copy">プロンプトをコピー</button></div><label>ChatGPT調査プロンプト<textarea id="research-prompt" rows="14" readonly placeholder="条件を選んでプロンプトを作成してください"></textarea></label><p id="research-prompt-status" class="status" role="status" aria-live="polite"></p>';deals.insertBefore(panel,importPanel);const updateVisibility=()=>{$('research-custom-region-wrap').hidden=$('research-region').value!=='custom';$('research-date-wrap').hidden=$('research-period').value!=='date'};['research-region','research-period'].forEach(id=>$(id).addEventListener('change',updateVisibility));updateVisibility();$('research-prompt-generate').addEventListener('click',()=>{$('research-prompt').value=buildResearchPrompt();$('research-prompt-status').textContent='プロンプトを作成しました。ChatGPTへ貼り付けてWeb調査を実行してください。'});$('research-prompt-copy').addEventListener('click',async()=>{const value=$('research-prompt').value;if(!value){$('research-prompt-status').textContent='先にプロンプトを作成してください。';return}try{await navigator.clipboard.writeText(value);$('research-prompt-status').textContent='プロンプトをコピーしました。'}catch{$('research-prompt-status').textContent='コピーできませんでした。プロンプト欄から手動でコピーしてください。'}})}
setupTravelResearchUI();
let selectedChatGptIndex=null,detailTargetIndex=null,pendingChatGptDetailFact=null;
function normalizeImportResults(payload){if(payload&&Array.isArray(payload.results))return payload.results.map(item=>normalizedChatGptImport(item));return [normalizedChatGptImport(payload)]}
function factDisplay(value){if(value===null||value===undefined||value==='')return '未確認';if(Array.isArray(value))return value.length?value.map(esc).join('、'):'未確認';return esc(String(value))}
function resultHasHotel(item){return typeof item?.hotel?.name==='string'&&item.hotel.name.trim()!==''}
function resultSourceLinks(item){const links=(item.sources||[]).filter(s=>/^https?:\/\//i.test(s.url||''));return links.length?links.map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.name||s.url)+'</a>').join('、'):'未確認'}
function renderImportResultCards(items){const cards=items.map((item,index)=>{const h=item.hotel,c=item.campaign,p=item.plan,hasHotel=resultHasHotel(item),selected=hasHotel&&selectedChatGptIndex!==null&&Number(selectedChatGptIndex)===index;return '<article class="card import-candidate '+(selected?'selected':'')+'"><h3>候補 '+(index+1)+'：'+factDisplay(h.name||c.name)+'</h3><div class="card-meta"><span>'+factDisplay(h.area||c.areas)+'</span><span class="badge">'+(hasHotel?'宿候補':'キャンペーン')+'</span></div><p><strong>料金：</strong>'+factDisplay(p.price)+(p.priceCondition?'（'+factDisplay(p.priceCondition)+'）':'')+'<br><strong>プラン：</strong>'+factDisplay(p.name)+'</p><p><strong>温泉：</strong>'+factDisplay(h.onsen)+'<br><strong>食事：</strong>'+factDisplay(h.meal)+'<br><strong>特徴：</strong>'+factDisplay(h.features)+'<br><strong>設備：</strong>'+factDisplay(h.facilities)+'</p><p><strong>キャンペーン：</strong>'+factDisplay(c.name)+'<br><strong>割引：</strong>'+factDisplay(c.discount)+'<br><strong>予約期間：</strong>'+factDisplay([c.bookingStart,c.bookingEnd].filter(Boolean).join('〜'))+'<br><strong>宿泊対象期間：</strong>'+factDisplay([c.stayStart,c.stayEnd].filter(Boolean).join('〜'))+'<br><strong>条件：</strong>'+factDisplay(c.conditions)+'</p><p><strong>情報確認日：</strong>'+factDisplay(item.checkedAt)+'<br><strong>情報源：</strong>'+resultSourceLinks(item)+'</p><div class="card-actions">'+(hasHotel?(selected?'<button class="primary" type="button" data-chat-import-detail="'+index+'">この宿を詳しく調べる</button><button class="primary" type="button" data-chat-import-use="'+index+'">旅行情報の登録へ反映</button>':'<button class="primary" type="button" data-chat-import-use="'+index+'">この宿を選ぶ</button>'):'<button class="primary" type="button" data-chat-import-use="'+index+'">この情報で投稿を作る</button><button class="secondary" type="button" data-chat-import-targets="'+index+'">このキャンペーンの対象宿を探す</button>')+'</div></article>'}).join('');$('chatgpt-import-preview').innerHTML='<div class="panel import-preview"><h3>調査結果（FACT確認）</h3><p class="muted">'+items.length+'件の候補です。ChatGPTが自動選択せず、人間が確認して選択してください。</p><div class="cards">'+cards+'</div><div id="chatgpt-followup-prompt"></div></div>'}
function campaignTargetPrompt(item){const c=item.campaign,count=selectedLabel('research-count',RESEARCH_OPTIONS.count);return ['楽天トラベル公式を最優先して、次のキャンペーンの対象宿を調査してください。','【キャンペーンFACT】','キャンペーン名：'+factDisplay(c.name),'割引内容：'+factDisplay(c.discount),'予約期間：'+factDisplay([c.bookingStart,c.bookingEnd].filter(Boolean).join('〜')),'宿泊対象期間：'+factDisplay([c.stayStart,c.stayEnd].filter(Boolean).join('〜')),'対象地域：'+factDisplay(c.areas),'利用条件：'+factDisplay(c.conditions),'情報源：'+resultSourceLinks(item),'希望件数：最大'+count,'【調査ルール】','確認できない情報は推測せずnullまたは空配列にしてください。条件に合う宿が少ない場合、条件を緩和せず確認できた件数だけ返してください。宿泊施設ごとにFACTと情報源URLを分けてください。','出力はresults配列を持つ指定JSON形式にしてください。',JSON.stringify({results:[CHATGPT_JSON_TEMPLATE]},null,2)].join('\n')}
function hotelDetailPrompt(item){const h=item.hotel,c=item.campaign,p=item.plan;return ['楽天トラベル公式を最優先して、次の宿を詳しく調査してください。','宿名：'+factDisplay(h.name),'地域：'+factDisplay(h.area),'楽天トラベルURL：'+factDisplay(h.rakutenUrl),'既存FACT：','特徴：'+factDisplay(h.features),'温泉：'+factDisplay(h.onsen),'食事：'+factDisplay(h.meal),'キャンペーン：'+factDisplay(c.name),'プラン：'+factDisplay(p.name),'【調査項目】','住所、特徴、温泉、食事、客室、設備、アクセス、料金、料金条件、プラン名、キャンペーン、割引内容、割引条件、予約期間、宿泊対象期間、楽天トラベルURL、情報源、確認日時を確認してください。','確認できない項目は推測せずnullまたは空配列にしてください。','出力はresults配列1件の指定JSON形式にしてください。',JSON.stringify({results:[CHATGPT_JSON_TEMPLATE]},null,2)].join('\n')}
function renderFollowupPrompt(prompt,title){const isHotelDetail=title==='宿詳細調査プロンプト';if(isHotelDetail){detailTargetIndex=selectedChatGptIndex;pendingChatGptDetailFact=null}$('chatgpt-followup-prompt').innerHTML='<div class="panel"><h3>'+esc(title)+'</h3><textarea id="chatgpt-followup-text" rows="14" readonly>'+esc(prompt)+'</textarea><button class="secondary" type="button" id="chatgpt-followup-copy">プロンプトをコピー</button>'+(isHotelDetail?'<hr><h4>ChatGPT詳細調査結果</h4><p class="muted">ChatGPTから返された旧1件形式またはresults配列のJSONを貼り付けてください。解析だけでは旅行情報を変更しません。</p><textarea id="chatgpt-detail-input" rows="10" placeholder="ChatGPTの詳細調査結果JSONを貼り付け"></textarea><div class="button-row"><button class="primary" type="button" id="chatgpt-detail-parse">解析する</button><button class="secondary" type="button" id="chatgpt-detail-clear">クリア</button></div><p id="chatgpt-detail-status" class="status" role="status" aria-live="polite"></p><div id="chatgpt-detail-preview"></div>':'')+'<p id="chatgpt-followup-status" class="status" role="status" aria-live="polite"></p></div>'}
function mergeDetailFacts(base,detail){const pick=(next,current)=>Array.isArray(next)?(next.length?next:current):(next!==null&&next!==undefined&&next!==''?next:current),merge=(a,b)=>Object.fromEntries(Object.keys(a).map(key=>[key,pick(b?.[key],a[key])]));const campaign=merge(base.campaign,detail.campaign);if(Object.prototype.hasOwnProperty.call(detail.campaign||{},'bookingStart'))campaign.bookingStart=detail.campaign.bookingStart;if(Object.prototype.hasOwnProperty.call(detail.campaign||{},'bookingEnd'))campaign.bookingEnd=detail.campaign.bookingEnd;return {...base,hotel:merge(base.hotel,detail.hotel),campaign,plan:merge(base.plan,detail.plan),sources:detail.sources?.length?detail.sources:base.sources,checkedAt:detail.checkedAt||base.checkedAt,notes:detail.notes?.length?detail.notes:base.notes}}
function renderDetailFactPreview(fact){const h=fact.hotel,c=fact.campaign,p=fact.plan,links=(fact.sources||[]).filter(s=>/^https?:\/\//i.test(s.url||'')).map(s=>'<li><a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.name||s.url)+'</a></li>').join('');$('chatgpt-detail-preview').innerHTML='<div class="panel import-preview"><h4>詳細FACTプレビュー</h4><p><strong>宿名：</strong>'+factDisplay(h.name)+'<br><strong>地域：</strong>'+factDisplay(h.area)+'<br><strong>住所：</strong>'+factDisplay(h.address)+'</p><p><strong>特徴：</strong>'+factDisplay(h.features)+'<br><strong>設備：</strong>'+factDisplay(h.facilities)+'<br><strong>温泉：</strong>'+factDisplay(h.onsen)+'<br><strong>食事：</strong>'+factDisplay(h.meal)+'</p><p><strong>キャンペーン：</strong>'+factDisplay(c.name)+'<br><strong>割引：</strong>'+factDisplay(c.discount)+'<br><strong>予約期間：</strong>'+factDisplay([c.bookingStart,c.bookingEnd].filter(Boolean).join('〜'))+'<br><strong>宿泊対象期間：</strong>'+factDisplay([c.stayStart,c.stayEnd].filter(Boolean).join('〜'))+'<br><strong>条件：</strong>'+factDisplay(c.conditions)+'</p><p><strong>プラン：</strong>'+factDisplay(p.name)+'<br><strong>料金：</strong>'+factDisplay(p.price)+'<br><strong>料金条件：</strong>'+factDisplay(p.priceCondition)+'</p><p><strong>情報確認日：</strong>'+factDisplay(fact.checkedAt)+'</p><p><strong>情報源：</strong></p><ul>'+(links||'<li>未確認</li>')+'</ul><p class="warning">詳細FACTは自動的に公式確認済みへ変更しません。内容を確認してから更新してください。</p><button class="primary" type="button" id="chatgpt-detail-update">旅行情報を更新</button></div>'}
function parseChatGptDetailResult(){try{const items=normalizeImportResults(extractChatGptJson($('chatgpt-detail-input').value));if(items.length!==1)throw new Error('詳細調査結果は1件のJSONにしてください。');pendingChatGptDetailFact=items[0];renderDetailFactPreview(pendingChatGptDetailFact);$('chatgpt-detail-status').textContent='詳細FACTを解析しました。内容を確認してください。'}catch(error){pendingChatGptDetailFact=null;$('chatgpt-detail-preview').innerHTML='';$('chatgpt-detail-status').textContent='解析できませんでした。JSON形式と候補数を確認してください。'+(error.message?' '+error.message:'')}}
function applyChatGptDetailResult(){const base=pendingChatGptImport?.[detailTargetIndex];if(!base||!pendingChatGptDetailFact){$('chatgpt-detail-status').textContent='先に詳細調査結果を解析してください。';return}const merged=mergeDetailFacts(base,pendingChatGptDetailFact),verification=$('verificationStatus')?.value||'unverified';useChatGptImport(merged);if($('verificationStatus'))$('verificationStatus').value=verification;currentChatGptImport=merged;pendingChatGptDetailFact=null;notice('詳細FACTを旅行情報フォームへ反映しました。内容を確認して保存してください。')}
function resultSourceText(item){const links=(item.sources||[]).filter(s=>/^https?:\/\//i.test(s.url||'')).map(s=>s.url);return links.length?links.join('、'):'未確認'}
const useChatGptImportWithSourceFix=useChatGptImport;useChatGptImport=function(f){useChatGptImportWithSourceFix(f);const source=(f?.sources||[]).find(s=>/^https?:\/\//i.test(s.url||''))?.url||f?.hotel?.rakutenUrl||'';if(source&&$('sourceUrl'))$('sourceUrl').value=source};
campaignTargetPrompt=function(item){const c=item.campaign,count=selectedLabel('research-count',RESEARCH_OPTIONS.count);return ['楽天トラベル公式を最優先して、次のキャンペーンの対象宿を調査してください。','【キャンペーンFACT】','キャンペーン名：'+factDisplay(c.name),'割引内容：'+factDisplay(c.discount),'予約期間：'+factDisplay([c.bookingStart,c.bookingEnd].filter(Boolean).join('〜')),'宿泊対象期間：'+factDisplay([c.stayStart,c.stayEnd].filter(Boolean).join('〜')),'対象地域：'+factDisplay(c.areas),'利用条件：'+factDisplay(c.conditions),'情報源：'+resultSourceText(item),'希望件数：最大'+count,'【調査ルール】','確認できない情報は推測せずnullまたは空配列にしてください。条件に合う宿が少ない場合、条件を緩和せず確認できた件数だけ返してください。宿泊施設ごとにFACTと情報源URLを分けてください。','出力はresults配列を持つ指定JSON形式にしてください。',JSON.stringify({results:[CHATGPT_JSON_TEMPLATE]},null,2)].join('\n')};
document.addEventListener('click',e=>{if(e.target.id==='research-prompt-generate'){const schema={results:[CHATGPT_JSON_TEMPLATE]};$('research-prompt').value=buildResearchPrompt()+'\n\n指定件数を上限とし、条件を満たす候補が少ない場合は無理に件数を埋めず、確認できた件数だけresultsへ入れてください。\n'+JSON.stringify(schema,null,2)}});
document.addEventListener('click',e=>{if(e.target.id==='chatgpt-import-parse'){try{const items=normalizeImportResults(extractChatGptJson($('chatgpt-import-input').value));if(!items.length)throw new Error('候補がありません。');pendingChatGptImport=items;selectedChatGptIndex=null;renderImportResultCards(items);$('chatgpt-import-status').textContent='複数候補を解析しました。FACTを確認して選択してください。'}catch(error){$('chatgpt-import-status').textContent='解析できませんでした。results配列または旧形式のJSONを確認してください。'+(error.message?' '+error.message:'')}}});
function getChatImportActionButton(target){return target instanceof Element?target.closest('[data-chat-import-use],[data-chat-import-targets],[data-chat-import-detail],#chatgpt-followup-copy,#chatgpt-detail-parse,#chatgpt-detail-clear,#chatgpt-detail-update'):null}
function handleChatImportAction(button){const useIndex=button.dataset.chatImportUse,targetIndex=button.dataset.chatImportTargets,detailIndex=button.dataset.chatImportDetail;if(useIndex!==undefined){const item=pendingChatGptImport?.[Number(useIndex)];if(!item)return;if(resultHasHotel(item)&&selectedChatGptIndex!==Number(useIndex)){selectedChatGptIndex=Number(useIndex);renderImportResultCards(pendingChatGptImport);return}useChatGptImport(item)}if(targetIndex!==undefined){const item=pendingChatGptImport?.[Number(targetIndex)];if(item)renderFollowupPrompt(campaignTargetPrompt(item),'対象宿調査プロンプト')}if(detailIndex!==undefined){const item=pendingChatGptImport?.[Number(detailIndex)];if(item)renderFollowupPrompt(hotelDetailPrompt(item),'宿詳細調査プロンプト')}if(button.id==='chatgpt-followup-copy'){const value=$('chatgpt-followup-text')?.value||'';copyTextWithFeedback(value,{status:$('chatgpt-followup-status')})}if(button.id==='chatgpt-detail-parse')parseChatGptDetailResult();if(button.id==='chatgpt-detail-clear'){$('chatgpt-detail-input').value='';$('chatgpt-detail-preview').innerHTML='';$('chatgpt-detail-status').textContent='';pendingChatGptDetailFact=null}if(button.id==='chatgpt-detail-update')applyChatGptDetailResult()}
document.addEventListener('click',e=>{const button=getChatImportActionButton(e.target);if(!button)return;e.preventDefault();handleChatImportAction(button);e.stopImmediatePropagation()},true);
document.addEventListener('click',e=>{const useIndex=e.target.dataset.chatImportUse,targetIndex=e.target.dataset.chatImportTargets,detailIndex=e.target.dataset.chatImportDetail;if(useIndex!==undefined){const item=pendingChatGptImport?.[Number(useIndex)];if(!item)return;if(resultHasHotel(item)&&selectedChatGptIndex!==Number(useIndex)){selectedChatGptIndex=Number(useIndex);renderImportResultCards(pendingChatGptImport);return}useChatGptImport(item)}if(targetIndex!==undefined){const item=pendingChatGptImport?.[Number(targetIndex)];if(item)renderFollowupPrompt(campaignTargetPrompt(item),'対象宿調査プロンプト')}if(detailIndex!==undefined){const item=pendingChatGptImport?.[Number(detailIndex)];if(item)renderFollowupPrompt(hotelDetailPrompt(item),'宿詳細調査プロンプト')}if(e.target.id==='chatgpt-followup-copy'){const value=$('chatgpt-followup-text')?.value||'';navigator.clipboard?.writeText(value).then(()=>{$('chatgpt-followup-status').textContent='プロンプトをコピーしました。'}).catch(()=>{$('chatgpt-followup-status').textContent='コピーできませんでした。'})}});
const useChatGptImportWithDates=useChatGptImport;useChatGptImport=function(f){useChatGptImportWithDates(f);if(f?.plan){if(f.plan.price!==null&&f.plan.price!==undefined&&f.plan.price!=='')$('currentPrice').value=Number(f.plan.price)||'';if(f.plan.name){const existing=$('attraction').value.trim();$('attraction').value=(existing?existing+'\n':'')+'プラン：'+f.plan.name+(f.plan.priceCondition?'（'+f.plan.priceCondition+'）':'')}}};

function mapImportedHotelFactsToForm(f){const h=f?.hotel||{},area=String(h.area||'').trim(),parts=area.split(/[・／/,、，]/).map(value=>value.trim()).filter(Boolean),facts=[...(Array.isArray(h.features)?h.features:[]),...(Array.isArray(h.facilities)?h.facilities:[]),h.onsen?'温泉：'+h.onsen:'',h.meal?'食事：'+h.meal:''].filter(Boolean);if(h.name&&$('facilityName'))$('facilityName').value=h.name;if(area&&$('region')){if(parts.length>1&&$('prefecture')){$('prefecture').value=parts[0];$('region').value=parts.slice(1).join('・')}else $('region').value=area}if(facts.length&&$('attraction'))$('attraction').value=facts.join('、')}
const useChatGptImportWithHotelFacts=useChatGptImport;useChatGptImport=function(f){useChatGptImportWithHotelFacts(f);mapImportedHotelFactsToForm(f)};

const THREAD_POST_FOCUS=[['deal','お得情報を前面に出す'],['charm','宿の魅力を前面に出す'],['onsen','温泉を前面に出す'],['meal','食事を前面に出す'],['family','家族旅行向け'],['couple','カップル旅行向け'],['solo','一人旅向け'],['pet','ペット旅行向け'],['balanced','お得＋宿の魅力をバランスよく'],['ai','AIに任せる']];
function savedResearchFacts(c){const f=c.chatgptResearchFacts&&typeof c.chatgptResearchFacts==='object'&&!Array.isArray(c.chatgptResearchFacts)?c.chatgptResearchFacts:{};return {hotel:f.hotel||{},campaign:f.campaign||{},plan:f.plan||{}}}
function confirmedPostingData(c){const f=savedResearchFacts(c),h=f.hotel||{},campaign=f.campaign||{},p=f.plan||{},conditionFacts=[c.campaignConditionsNew,c.dealConditions,...(Array.isArray(campaign.conditions)?campaign.conditions:[])].filter(Boolean);return {name:c.facilityName||h.name||'',area:[c.prefecture,c.region].filter(Boolean).join('・')||h.area||'',attraction:c.attraction||'',discount:c.discountText||c.dealText||campaign.discount||'',campaign:c.campaignName||campaign.name||'',conditions:conditionFacts.join('\n'),start:c.startAt||campaign.bookingStart||'',end:c.endAt||campaign.bookingEnd||'',stay:c.verificationStatus==='verified'&&campaign.stayStart&&campaign.stayEnd?[campaign.stayStart,campaign.stayEnd].join('〜'):'',price:c.currentPrice!==''&&c.currentPrice!==null&&c.currentPrice!==undefined?c.currentPrice:(p.price??''),priceCondition:p.priceCondition||'',onsen:h.onsen||'',meal:h.meal||'',features:Array.isArray(h.features)?h.features.join('、'):'',facilities:Array.isArray(h.facilities)?h.facilities.join('、'):'',audience:c.targetAudience||'',purpose:c.purpose||''}}
function focusAvailable(data,focus){const text=[data.attraction,data.features,data.onsen,data.meal,data.facilities,data.audience,data.purpose].filter(Boolean).join(' ');if(focus==='onsen')return Boolean(data.onsen||/温泉|露天/.test(text));if(focus==='meal')return Boolean(data.meal||/食事|料理|会席|朝食|夕食/.test(text));if(focus==='pet')return /ペット|愛犬|犬/.test(text);if(focus==='family')return Boolean(data.audience&&/家族|子ども|子連れ/.test(data.audience)||/家族|子ども|子連れ/.test(text));if(focus==='couple')return Boolean(data.audience&&/カップル|夫婦/.test(data.audience)||/カップル|夫婦/.test(text));if(focus==='solo')return Boolean(data.audience&&/一人|ひとり/.test(data.audience)||/一人|ひとり/.test(text));return true}
function priceIsSafeForPost(data){const price=String(data.price??'').trim(),condition=String(data.priceCondition??'').trim();if(!price)return false;if(/使用不可|該当しない|未確認|確認できない|対象外|一致しない|別の料金|別料金|特定日の予約可能料金ではない|予約可能料金ではない|価格帯/.test(condition))return false;return true}
function priceNeedsReview(data){return String(data.price??'').trim()!==''&&!priceIsSafeForPost(data)}
function readerFactParts(text){return String(text??'').split(/[\n、。]+/).map(v=>v.trim()).filter(Boolean).filter(v=>!/(verificationStatus|JSON|システム|AI向け|調査手順|投稿前に.*確認|混同しない|null|自動的|内部向け|開発者向け)/i.test(v)).map(v=>v.length>70?v.slice(0,70)+'…':v)}
function uniqueFactParts(parts,limit=3){return [...new Set(parts.flatMap(readerFactParts))].filter(Boolean).slice(0,limit)}
function generateSavedPost(c,d){const data=confirmedPostingData(c),focus=d.focus||'balanced',hasUrl=Boolean(c.threadsShortUrl),highlights={deal:uniqueFactParts([data.attraction,data.features,data.facilities,data.meal,data.onsen],2),charm:uniqueFactParts([data.attraction,data.features,data.facilities,data.onsen,data.meal],3),onsen:uniqueFactParts([data.onsen,data.attraction,data.features],2),meal:uniqueFactParts([data.meal,data.attraction,data.onsen],2),family:uniqueFactParts([data.audience,data.attraction,data.features,data.meal],2),couple:uniqueFactParts([data.audience,data.attraction,data.meal,data.onsen],2),solo:uniqueFactParts([data.audience,data.attraction,data.onsen,data.meal],2),pet:uniqueFactParts([data.features,data.facilities,data.attraction,data.meal],3),balanced:uniqueFactParts([data.attraction,data.features,data.onsen,data.meal,data.facilities],3),ai:uniqueFactParts([data.attraction,data.features,data.onsen,data.meal,data.facilities],3)}[focus]||[];if(!focusAvailable(data,focus))return {body:data.name+'について、選択したテーマの確認済みFACTは登録されていません。別の見せ方を選ぶか、公式情報を確認してください。',reply1:'選択したテーマの情報は未確認です。',reply2:''};const intro={deal:data.area+'で、お得情報を確認しました。',charm:data.area+'で宿を探している方へ。',onsen:data.area+'で温泉を楽しみたい方へ。',meal:data.area+'で食事を楽しむ旅を考えている方へ。',family:data.area+'で家族旅行を考えている方へ。',couple:data.area+'で二人の旅を考えている方へ。',solo:data.area+'で一人旅を考えている方へ。',pet:data.area+'でペットとの旅行を考えている方へ。',balanced:data.area+'で宿を探している方へ。',ai:data.area+'の旅行情報をまとめました。'}[focus];const facts=[];if(data.campaign||data.discount)facts.push([data.campaign,data.discount].filter(Boolean).join('：'));facts.push(...highlights);if(priceIsSafeForPost(data))facts.push('料金：'+fmt(data.price)+(data.priceCondition?'（'+data.priceCondition+'）':''));if(data.start)facts.push('予約開始：'+data.start);if(data.end)facts.push('予約終了：'+data.end);if(data.stay)facts.push('宿泊対象期間：'+data.stay);const readerConditions=uniqueFactParts([data.conditions],1);if(readerConditions.length)facts.push('条件：'+readerConditions[0]);const body=[intro,data.name,facts.join('\n'),focus==='deal'?'詳しい条件は公式情報をご確認ください。':'気になる条件は公式情報をご確認ください。'].filter(Boolean).join('\n\n').slice(0,350);const reply1=['詳しいプラン・空室はこちら👇',hasUrl?c.threadsShortUrl:'Threads用URL未登録',readerConditions.length?'※'+readerConditions[0]:'',hasUrl?'PR':''].filter(Boolean).join('\n');const reply2=d.format==='multi_reply'?highlights.slice(0,2).join('\n'):'';return {body: d.format==='direct_link'&&hasUrl?body+'\n\n'+c.threadsShortUrl:body,reply1,reply2}}
function renderSavedPost(c){let d=drafts[c.id]||{focus:'balanced',tone:'natural',format:'reply_link'},g=generateSavedPost(c,d);drafts[c.id]={...d,...g,angle:d.angle||'location'};const x=drafts[c.id],target=$('compose-'+c.id),options=THREAD_POST_FOCUS.map(([v,l])=>'<option value="'+v+'" '+(x.focus===v?'selected':'')+'>'+l+'</option>').join('');if(!target)return;target.innerHTML='<div class="panel"><h3>Threads投稿文を作る</h3>'+(c.verificationStatus!=='verified'?'<div class="warning">この旅行情報には未確認情報があります。投稿前に公式情報を確認してください。</div>':'')+(!priceIsSafeForPost(confirmedPostingData(c))?'<div class="warning">料金情報に確認が必要なため、投稿文では使用していません。</div>':'')+(c.affiliateUrl&&!c.threadsShortUrl?'<div class="warning">Threads用短縮URLが未登録です。情報元URLや長いアフィリエイトURLは自動使用しません。</div>':'')+'<div class="grid three"><label>投稿の見せ方<select data-c="focus" data-id="'+c.id+'">'+options+'</select></label><label>トーン<select data-c="tone" data-id="'+c.id+'"><option value="natural" '+(x.tone==='natural'?'selected':'')+'>自然</option><option value="strong" '+(x.tone==='strong'?'selected':'')+'>少し強め</option></select></label><label>投稿形式<select data-c="format" data-id="'+c.id+'"><option value="reply_link" '+(x.format==='reply_link'?'selected':'')+'>本文＋リンク付き返信</option><option value="direct_link" '+(x.format==='direct_link'?'selected':'')+'>本文に直接リンク</option><option value="multi_reply" '+(x.format==='multi_reply'?'selected':'')+'>本文＋返信1＋返信2</option></select></label></div><div class="generated"><label>本文<textarea data-t="body" data-id="'+c.id+'" rows="7">'+esc(x.body)+'</textarea><button class="secondary copy" type="button" data-tcopy="body" data-id="'+c.id+'">本文をコピー</button><label>返信1<textarea data-t="reply1" data-id="'+c.id+'" rows="5">'+esc(x.reply1)+'</textarea><button class="secondary copy" type="button" data-tcopy="reply1" data-id="'+c.id+'">返信1をコピー</button>'+(x.format==='multi_reply'?'<label>返信2<textarea data-t="reply2" data-id="'+c.id+'" rows="4">'+esc(x.reply2)+'</textarea><button class="secondary copy" type="button" data-tcopy="reply2" data-id="'+c.id+'">返信2をコピー</button>':'')+'</div><div class="card-actions"><button class="primary" type="button" data-a="regenerate" data-id="'+c.id+'">再生成</button><button class="secondary" type="button" data-a="clear-draft" data-id="'+c.id+'">クリア</button></div></div>'}
function candidateFactSummary(c){const f=savedResearchFacts(c),h=f.hotel||{},p=f.plan||{},campaign=f.campaign||{},parts=[c.campaignName||campaign.name,c.discountText||c.dealText||campaign.discount,p.name?'プラン：'+p.name:'',p.price!==null&&p.price!==undefined&&p.price!==''?'料金：'+p.price:'',p.priceCondition?'条件：'+p.priceCondition:'',h.onsen?'温泉：'+h.onsen:'',h.meal?'食事：'+h.meal:''].filter(Boolean);return parts}
const legacyRenderCandidates=renderCandidates;renderCandidates=function(){legacyRenderCandidates();document.querySelectorAll('[data-a="compose"]').forEach(button=>button.textContent='Threads投稿文を作る');document.querySelectorAll('#candidate-list .card').forEach((card,index)=>{const summary=candidateFactSummary(state.candidates[index]);if(!summary.length)return;const block=document.createElement('p');block.className='muted';block.dataset.factSummary='true';block.textContent=summary.join('\n');const actions=card.querySelector('.card-actions');if(actions)actions.before(block)})};
const legacyCompose=compose;compose=renderSavedPost;
document.addEventListener('click',e=>{const id=e.target.dataset.id;if(!id)return;if(e.target.dataset.a==='regenerate'){const c=state.candidates.find(x=>x.id===id);if(c)renderSavedPost(c)}if(e.target.dataset.a==='clear-draft'){drafts[id]={focus:'balanced',tone:'natural',format:'reply_link'};const c=state.candidates.find(x=>x.id===id);if(c)renderSavedPost(c)}});
const renderSavedPostWithRecordActions=renderSavedPost;renderSavedPost=function(c){renderSavedPostWithRecordActions(c);const actions=$('compose-'+c.id)?.querySelector('.card-actions');if(actions&&!actions.querySelector('[data-a="ready"]'))actions.insertAdjacentHTML('beforeend','<button class="primary" type="button" data-a="ready" data-id="'+c.id+'">投稿準備完了として保存</button><button class="secondary" type="button" data-a="posted" data-id="'+c.id+'">投稿済みにする</button>')};compose=renderSavedPost;
render();
document.addEventListener('click',e=>{if(e.target.dataset.a==='edit'){setTimeout(()=>{const candidate=state.candidates.find(x=>x.id===$('edit-id').value);if(candidate&&$('campaignConditionsNew'))$('campaignConditionsNew').value=candidate.campaignConditions??candidate.campaignConditionsNew??''},1)}});
document.addEventListener('click',e=>{if(e.target.id==='research-prompt-copy'){e.preventDefault();e.stopImmediatePropagation();const value=$('research-prompt')?.value||'';if(value)copyTextWithFeedback(value,{status:$('research-prompt-status')});else $('research-prompt-status').textContent='先にプロンプトを作成してください。'}if(e.target.classList?.contains('copy')){e.preventDefault();e.stopImmediatePropagation();const id=e.target.dataset.id,c=state.candidates.find(x=>x.id===id);if(!c)return;sync(id);copyTextWithFeedback(drafts[id]?.[e.target.dataset.tcopy]||'',{status:$('notice')})}},true);
const renderSavedPostWithSavedDraft=renderSavedPost;renderSavedPost=function(c){const hadDraft=Boolean(drafts[c.id]);renderSavedPostWithSavedDraft(c);if(!hadDraft&&c.post&&typeof c.post==='object'){drafts[c.id]={...drafts[c.id],body:c.post.body||'',reply1:c.post.reply1||'',reply2:c.post.reply2||'',focus:c.focus||drafts[c.id].focus,tone:c.tone||drafts[c.id].tone,format:c.format||drafts[c.id].format};document.querySelectorAll('[data-t][data-id="'+c.id+'"]').forEach(field=>{if(Object.prototype.hasOwnProperty.call(drafts[c.id],field.dataset.t))field.value=drafts[c.id][field.dataset.t]||''})}};compose=renderSavedPost;

const FLYER_ANGLES=[['balanced','お得＋宿の魅力'],['meal','食事重視'],['onsen','温泉重視'],['pet','ペット旅行向け']];
const FLYER_RATIOS=[['1:1','1:1　SNS正方形'],['4:5','4:5　SNS縦長'],['9:16','9:16　Threads / Stories向け縦長']];
const FLYER_DESIGNS=[['travel_ad','旅行広告風'],['luxury','上品・高級感'],['friendly','やさしい・親しみやすい'],['simple','シンプル・読みやすい']];
function flyerTextFacts(c,angle){const data=confirmedPostingData(c),base={balanced:uniqueFactParts([data.attraction,data.features,data.meal,data.onsen,data.facilities],4),meal:uniqueFactParts([data.meal,data.attraction,data.onsen,data.features],4),onsen:uniqueFactParts([data.onsen,data.attraction,data.meal,data.features],4),pet:uniqueFactParts([data.features,data.facilities,data.attraction,data.meal,data.onsen],4)}[angle]||[];return {data,highlights:base}}
function buildFlyerPrompt(c,settings){const {data,highlights}=flyerTextFacts(c,settings.angle),ratio=FLYER_RATIOS.find(x=>x[0]===settings.aspectRatio)?.[1]||settings.aspectRatio,design=FLYER_DESIGNS.find(x=>x[0]===settings.design)?.[1]||settings.design,angle=FLYER_ANGLES.find(x=>x[0]===settings.angle)?.[1]||settings.angle,lines=[data.name,data.area, data.campaign&&data.discount?[data.campaign,data.discount].join('：'):data.discount||'',...highlights,priceIsSafeForPost(data)?'料金：'+fmt(data.price)+(data.priceCondition?'（'+data.priceCondition+'）':''):'',data.conditions?'※'+uniqueFactParts([data.conditions],1)[0]:'','PR'].filter(Boolean);return ['楽天トラベルの宿泊情報を紹介するSNS向け旅行広告画像を作成してください。','【見せ方】'+angle,'【画像比率】'+ratio,'【画像内テキスト】',lines.join('\n'),'【ビジュアル指示】',design+'の旅行広告。保存されたFACTから確認できる魅力を中心に、情報を詰め込みすぎず読みやすく配置してください。宿名・地域・料理・温泉・ペット対応など、入力されている内容だけを使用してください。','【重要】','FACTとデザイン指示を混同せず、数字・名称・条件を書き換えないでください。「最大30%OFF」を「30%OFF」や「全プラン30%OFF」に変更しないでください。入力されていない設備・料理・客室・景観・サービスを追加しないでください。生成された背景・人物・料理・温泉などは広告表現用のイメージであり、実在施設の正確な写真として表現しないでください。URLやQRコードは生成しないでください。日本語テキストを正確に描画し、生成後に人間が文字内容を確認してください。'].join('\n\n')}
function persistFlyer(c,settings,prompt){c.flyer={enabled:true,angle:settings.angle,aspectRatio:settings.aspectRatio,design:settings.design,prompt,updatedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(state))}
function flyerCard(c){const card=document.querySelector('[data-a="compose"][data-id="'+c.id+'"]')?.closest('article.card');return card}
function removeFlyerPanel(c){document.querySelector('#flyer-'+c.id)?.remove()}
function renderFlyerOffer(c){const card=flyerCard(c);if(!card||card.querySelector('[data-flyer-offer]')||c.flyer?.enabled)return;const area=card.querySelector('#compose-'+c.id);if(!area)return;area.insertAdjacentHTML('afterend','<div class="panel" data-flyer-offer="true"><h4>この旅行情報の紹介チラシも作りますか？</h4><p class="muted">保存済みFACTから、画像生成AIへ渡すプロンプトを作成できます。</p><div class="button-row"><button class="primary" type="button" data-a="flyer-open" data-id="'+c.id+'">紹介チラシを作る</button><button class="secondary" type="button" data-a="flyer-dismiss" data-id="'+c.id+'">作らない</button></div></div>')}
function renderFlyerUI(c){const card=flyerCard(c);if(!card)return;removeFlyerPanel(c);let panel=card.querySelector('#flyer-'+c.id);if(!panel){panel=document.createElement('div');panel.id='flyer-'+c.id;panel.className='panel';card.appendChild(panel)}const previous=c.flyer?.enabled?c.flyer:{};panel.innerHTML='<h4>紹介チラシ</h4><p class="muted">保存済みFACTを選別して、ChatGPTやGeminiへ貼り付けるプロンプトを作成します。画像生成APIは使用しません。</p><div class="grid three"><label>チラシの見せ方<select data-flyer="angle">'+FLYER_ANGLES.map(x=>'<option value="'+x[0]+'" '+(previous.angle===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label><label>画像比率<select data-flyer="aspectRatio">'+FLYER_RATIOS.map(x=>'<option value="'+x[0]+'" '+(previous.aspectRatio===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label><label>デザイン<select data-flyer="design">'+FLYER_DESIGNS.map(x=>'<option value="'+x[0]+'" '+(previous.design===x[0]?'selected':'')+'>'+x[1]+'</option>').join('')+'</select></label></div><div class="button-row"><button class="primary" type="button" data-a="flyer-generate" data-id="'+c.id+'">チラシ作成プロンプトを作る</button><button class="secondary" type="button" data-a="flyer-copy" data-id="'+c.id+'">プロンプトをコピー</button><button class="secondary" type="button" data-a="flyer-clear" data-id="'+c.id+'">クリア</button></div><textarea data-flyer="prompt" rows="18" placeholder="設定してプロンプトを作成してください">'+esc(previous.prompt||'')+'</textarea><p class="status" data-flyer-status role="status" aria-live="polite"></p><p class="muted">画像内の日本語、FACT、条件は生成後に人間が確認してください。</p>'}
function currentFlyerSettings(panel){return {angle:panel.querySelector('[data-flyer="angle"]')?.value||'balanced',aspectRatio:panel.querySelector('[data-flyer="aspectRatio"]')?.value||'4:5',design:panel.querySelector('[data-flyer="design"]')?.value||'travel_ad'}}
function flyerPanelFor(id){return document.querySelector('#flyer-'+id)}
document.addEventListener('click',e=>{const action=e.target.dataset.a,id=e.target.dataset.id;if(!id)return;const c=state.candidates.find(x=>x.id===id);if(!c)return;if(action==='ready'){setTimeout(()=>{if(c.status==='ready')renderFlyerOffer(c)},0)}if(action==='flyer-dismiss'){removeFlyerPanel(c);notice('紹介チラシは作成しませんでした。')}if(action==='flyer-open'){renderFlyerUI(c)}if(action==='flyer-generate'){const panel=flyerPanelFor(id);if(!panel)return;const settings=currentFlyerSettings(panel),prompt=buildFlyerPrompt(c,settings);panel.querySelector('[data-flyer="prompt"]').value=prompt;persistFlyer(c,settings,prompt);panel.querySelector('[data-flyer-status]').textContent='プロンプトを保存しました。FACTは変更していません。'}if(action==='flyer-copy'){const panel=flyerPanelFor(id);if(panel)copyTextWithFeedback(panel.querySelector('[data-flyer="prompt"]')?.value,{status:panel.querySelector('[data-flyer-status]')})}if(action==='flyer-clear'){const panel=flyerPanelFor(id);if(panel){panel.querySelector('[data-flyer="prompt"]').value='';panel.querySelector('[data-flyer-status]').textContent='';if(c.flyer){c.flyer.prompt='';c.flyer.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state))}}}},false);
const renderCandidatesWithFlyer=renderCandidates;renderCandidates=function(){renderCandidatesWithFlyer();state.candidates.filter(c=>c.flyer?.enabled).forEach(c=>{const card=flyerCard(c),actions=card?.querySelector('.card-actions');if(actions&&!actions.querySelector('[data-a="flyer-open"]'))actions.insertAdjacentHTML('beforeend','<button class="secondary" type="button" data-a="flyer-open" data-id="'+c.id+'">紹介チラシ</button>')})};render();
function generateFlyerShortPost(c,d){const data=confirmedPostingData(c),focus=d.focus||'balanced',hasUrl=Boolean(c.threadsShortUrl),focusFacts={deal:uniqueFactParts([data.discount,data.campaign,data.attraction],1),charm:uniqueFactParts([data.attraction,data.features,data.facilities],1),onsen:uniqueFactParts([data.onsen,data.attraction],1),meal:uniqueFactParts([data.meal,data.attraction],1),family:uniqueFactParts([data.attraction,data.features,data.meal],1),couple:uniqueFactParts([data.attraction,data.meal,data.onsen],1),solo:uniqueFactParts([data.attraction,data.onsen,data.meal],1),pet:uniqueFactParts([data.features,data.facilities,data.attraction],1),balanced:uniqueFactParts([data.attraction,data.features,data.onsen,data.meal],1),ai:uniqueFactParts([data.discount,data.attraction,data.features,data.onsen,data.meal],1)}[focus]||[];if(!focusAvailable(data,focus))return {body:data.name+'について、選択したテーマのFACTは未確認です。',reply1:'詳しい情報は公式ページでご確認ください。\n'+(hasUrl?c.threadsShortUrl:'Threads用URL未登録')+(hasUrl?'\nPR':''),reply2:''};const lead={deal:data.area+'のお得な宿情報をチェック。',charm:data.area+'で宿の魅力を楽しむ旅へ。',onsen:data.area+'で温泉を楽しむ旅へ。',meal:data.area+'で料理を楽しむ旅へ。',family:data.area+'で家族旅行を考えている方へ。',couple:data.area+'で二人の旅を考えている方へ。',solo:data.area+'で一人旅を考えている方へ。',pet:data.area+'で愛犬と楽しむ宿旅へ。',balanced:data.area+'で宿の魅力を楽しむ旅へ。',ai:data.area+'の旅行情報を短くまとめました。'}[focus];const strong=[data.discount||data.campaign,focusFacts[0]].filter(Boolean).join('。');const body=[data.name?data.name+'｜'+lead:lead,strong].filter(Boolean).join('\n').slice(0,120);const conditions=uniqueFactParts([data.conditions],1);const reply1=['詳しいプラン・空室はこちら👇',hasUrl?c.threadsShortUrl:'Threads用URL未登録',conditions.length?'※'+conditions[0]:'',hasUrl?'PR':''].filter(Boolean).join('\n');return {body,reply1,reply2:''}}
const generateSavedPostBeforeFlyer=generateSavedPost;generateSavedPost=function(c,d){return c.flyer?.enabled===true?generateFlyerShortPost(c,d):generateSavedPostBeforeFlyer(c,d)};
const renderSavedPostWithFlyerShortBody=renderSavedPost;renderSavedPost=function(c){renderSavedPostWithFlyerShortBody(c);if(c.flyer?.enabled!==true)return;const d=drafts[c.id]||{focus:'balanced',tone:'natural',format:'reply_link'},g=generateFlyerShortPost(c,d);drafts[c.id]={...d,...g};const body=document.querySelector('[data-t="body"][data-id="'+c.id+'"]'),reply1=document.querySelector('[data-t="reply1"][data-id="'+c.id+'"]');if(body)body.value=g.body;if(reply1)reply1.value=g.reply1};compose=renderSavedPost;
const renderSavedPostWithFlyerChoice=renderSavedPost;function renderFlyerChoice(c){const target=$('compose-'+c.id);if(!target)return;target.innerHTML='<div class="panel"><h3>投稿作成の準備</h3><p>紹介チラシを作りますか？</p><div class="button-row"><button class="primary" type="button" data-a="flyer-choice" data-choice="yes" data-id="'+c.id+'">紹介チラシを作る</button><button class="secondary" type="button" data-a="flyer-choice" data-choice="no" data-id="'+c.id+'">作らない</button></div></div>'}compose=renderFlyerChoice;
document.addEventListener('click',e=>{if(e.target.dataset.a!=='flyer-choice')return;const id=e.target.dataset.id,c=state.candidates.find(x=>x.id===id);if(!c)return;c.flyer={...(c.flyer||{}),enabled:e.target.dataset.choice==='yes'};drafts[id]={focus:c.focus||'balanced',tone:c.tone||'natural',format:c.format||'reply_link'};renderSavedPostWithFlyerChoice(c);if(e.target.dataset.choice==='yes')renderFlyerUI(c)});
function candidateRakutenOfficialUrl(c){const facts=c.chatgptResearchFacts&&typeof c.chatgptResearchFacts==='object'?c.chatgptResearchFacts:{};const hotel=facts.hotel&&typeof facts.hotel==='object'?facts.hotel:{};return [hotel.rakutenUrl,c.sourceUrl].map(value=>String(value||'').trim()).find(validHttpUrl)||''}
const renderCandidatesWithOfficialLink=renderCandidates;renderCandidates=function(){renderCandidatesWithOfficialLink();document.querySelectorAll('#candidate-list .card').forEach((card,index)=>{const url=candidateRakutenOfficialUrl(state.candidates[index]);if(!url||card.querySelector('[data-rakuten-official]'))return;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.className='secondary';link.dataset.rakutenOfficial='true';link.textContent='楽天トラベルで確認 ↗';const warning=card.querySelector('.warning'),actions=card.querySelector('.card-actions');if(warning)warning.insertAdjacentElement('afterend',link);else if(actions)actions.insertAdjacentElement('beforebegin',link)})};render();
function isRakutenOfficialUrl(value){try{const url=new URL(String(value||''));const host=url.hostname.toLowerCase();return (url.protocol==='http:'||url.protocol==='https:')&&(host==='hotel.travel.rakuten.co.jp'||host==='travel.rakuten.co.jp'||host.endsWith('.travel.rakuten.co.jp'))}catch{return false}}
const normalizedChatGptImportBeforeRakutenUrlCheck=normalizedChatGptImport;normalizedChatGptImport=function(data){const facts=normalizedChatGptImportBeforeRakutenUrlCheck(data);if(facts.hotel)facts.hotel.rakutenUrl=isRakutenOfficialUrl(facts.hotel.rakutenUrl)?facts.hotel.rakutenUrl:'';return facts};
const useChatGptImportBeforeRakutenUrlPriority=useChatGptImport;useChatGptImport=function(f){useChatGptImportBeforeRakutenUrlPriority(f);const url=isRakutenOfficialUrl(f?.hotel?.rakutenUrl)?f.hotel.rakutenUrl:(f?.sources||[]).find(s=>isRakutenOfficialUrl(s?.url))?.url||'';if(url&&$('sourceUrl'))$('sourceUrl').value=url};
candidateRakutenOfficialUrl=function(c){const facts=c.chatgptResearchFacts&&typeof c.chatgptResearchFacts==='object'?c.chatgptResearchFacts:{},hotel=facts.hotel&&typeof facts.hotel==='object'?facts.hotel:{};return [hotel.rakutenUrl,c.sourceUrl].find(isRakutenOfficialUrl)||''};
document.addEventListener('click',e=>{if(e.target.dataset.a!=='edit')return;setTimeout(()=>{const c=state.candidates.find(x=>x.id===$('edit-id')?.value),url=candidateRakutenOfficialUrl(c||{});if(url&&$('sourceUrl'))$('sourceUrl').value=url},0)});
render();
const buildFlyerPromptBeforeIllustrationSafety=buildFlyerPrompt;buildFlyerPrompt=function(c,settings){return buildFlyerPromptBeforeIllustrationSafety(c,settings)+'\n\n【イラスト表現の必須条件】\nビジュアルは実写・写真風ではなく、明確にイラストと分かる、明るく親しみやすい旅行広告イラストとして描画してください。柔らかい描画と適度なデフォルメを用い、旅行広告風はレイアウトと情報設計を意味するものとして、写真風の旅行広告にはしないでください。\n\n【背景と描写の制限】\n実在施設そのものを想像して描かないでください。宿の建物、外観、玄関、ロビー、客室、浴場、露天風呂、レストランなど、実在施設の設備と誤認される具体的な建物・施設描写は生成しないでください。宿の外観の代わりに、保存済みFACTで確認できる範囲の地域・旅行の雰囲気を伝える、柔らかな風景イラストを背景に使用してください。地域名だけから特定の観光地、ランドマーク、海、山、温泉街などを推測して追加しないでください。保存済みFACTに具体的な景観がない場合は、特定場所を示さない抽象的な旅行背景にしてください。\n\n料理、人物、ペットを描く場合も、保存済みFACTに確認できる内容だけを使用してください。料理内容が具体的でない場合は、具体的な食材を描かず、抽象的な家庭料理などのイメージにとどめてください。人物やペットは実在スタッフ・宿泊客・動物を再現せず、広告表現用のイメージイラストとして描いてください。保存済みFACTにない設備、食材、景観、人物、ペット、サービスを追加しないでください。\n\n画像内テキストに「※画像はイメージです」を読み取れる大きさで必ず表示してください。PR表記も維持してください。';};
