const KEY='rakutenTravelPerformanceAssistantV1';
const ANGLES=[['food','料理'],['onsen','温泉・露天風呂'],['room','部屋・眺望'],['family','子連れ・家族旅行'],['couple','夫婦・カップル'],['themepark','テーマパーク周辺'],['location','観光・立地'],['season','季節・イベント'],['coupon','クーポン・割引'],['limited','期間限定プラン'],['ranking','ランキング・評価'],['transport','交通とのセット']];
const L={unverified:'未確認',verified:'公式確認済み',expired:'期限切れ',recheck:'要再確認',draft:'下書き',ready:'投稿準備完了',posted:'投稿済み',reply_link:'本文＋リンク付き返信',direct_link:'本文に直接リンク',multi_reply:'本文＋返信1＋返信2',natural:'自然',strong:'少し強め'};
let state=load(), drafts={};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])), fmt=n=>n===''||n==null?'未入力':Number(n).toLocaleString('ja-JP');
function load(){try{let raw=localStorage.getItem(KEY);if(!raw){let d={settings:{},candidates:[],history:[],sales:[]};localStorage.setItem(KEY,JSON.stringify(d));return d}let d=JSON.parse(raw);if(d&&typeof d==='object'&&d.settings&&Array.isArray(d.candidates)&&Array.isArray(d.history)&&Array.isArray(d.sales))return d}catch(e){}return {settings:{},candidates:[],history:[],sales:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function notice(t){$('notice').textContent=t;setTimeout(()=>{$('notice').textContent=''},3000)}
function sum(rows,k){return rows.reduce((a,r)=>a+(r.metrics?.[k]==null||r.metrics?.[k]===''?0:Number(r.metrics[k])||0),0)}
function nav(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));render()}
function render(){renderStats();renderCandidates();renderHistory();renderAnalysis()}
function renderStats(){let p=state.candidates.filter(c=>c.status==='posted'),a=[['投稿候補数',state.candidates.length],['投稿済み数',p.length],['総本文表示数',sum(p,'impressions')],['総クリック数',sum(p,'clicks')],['予約成果件数',sum(p,'bookings')],['総報酬額',sum(p,'reward')]];$('stats').innerHTML=a.map(x=>'<div class="stat"><strong>'+fmt(x[1])+'</strong><span>'+x[0]+'</span></div>').join('')}
function renderCandidates(){let b=$('candidate-list');if(!state.candidates.length){b.innerHTML='<div class="empty">旅行情報を登録すると、ここに投稿候補が表示されます。</div>';return}b.innerHTML=state.candidates.map(c=>'<article class="card"><h3>'+esc(c.facilityName)+'</h3><div class="card-meta"><span>'+esc([c.prefecture,c.region].filter(Boolean).join('・'))+'</span><span class="badge">'+(L[c.angle]||'切り口未選択')+'</span><span class="badge '+(c.verificationStatus==='verified'?'good':'warn')+'">'+L[c.verificationStatus]+'</span><span class="badge">'+L[c.status]+'</span></div><p class="muted">作成：'+new Date(c.createdAt).toLocaleString('ja-JP')+'</p>'+(c.verificationStatus!=='verified'?'<div class="warning">未確認情報があります。価格・割引・期限は公式確認後に使用してください。</div>':'')+'<div class="card-actions"><button class="primary" data-a="compose" data-id="'+c.id+'">投稿を作成</button><button class="secondary" data-a="edit" data-id="'+c.id+'">詳細・編集</button><button class="danger" data-a="delete" data-id="'+c.id+'">削除</button></div><div id="compose-'+c.id+'"></div>'+(c.status==='posted'?metrics(c):'')+'</article>').join('')}
function metrics(c){let m=c.metrics||{};return '<details class="panel"><summary>成果を入力・更新</summary><div class="inline-form">'+[['impressions','本文表示数'],['replyImpressions','返信1表示数'],['reply2Impressions','返信2表示数'],['likes','本文いいね'],['replyLikes','返信いいね'],['replies','返信数'],['reposts','再投稿数'],['clicks','クリック数'],['bookings','予約成果件数'],['sales','売上額'],['reward','報酬額']].map(x=>'<label>'+x[1]+'<input type="number" min="0" data-metric="'+x[0]+'" data-id="'+c.id+'" value="'+(m[x[0]]??'')+'"></label>').join('')+'</div></details>'}
function renderHistory(){let b=$('history-list');b.innerHTML=state.history.length?state.history.map(h=>'<article class="card"><h3>'+esc(h.facilityName)+'</h3><div class="card-meta"><span>'+L[h.format]+'</span><span>'+new Date(h.postedAt).toLocaleString('ja-JP')+'</span></div><details><summary>投稿内容</summary><p>'+esc(h.body).replaceAll('\n','<br>')+'</p><p>'+esc(h.reply1).replaceAll('\n','<br>')+'</p>'+(h.reply2?'<p>'+esc(h.reply2).replaceAll('\n','<br>')+'</p>':'')+'</details></article>').join(''):'<div class="empty">投稿済みの履歴はありません。</div>'}
function renderAnalysis(){let rows=[['format','投稿形式別',Object.keys({reply_link:1,direct_link:1,multi_reply:1})],['angle','切り口別',ANGLES.map(x=>x[0])]];$('analysis-content').innerHTML=rows.map(r=>'<div class="panel"><h3>'+r[1]+'</h3><table class="metric-table"><thead><tr><th>分類</th><th>投稿数</th><th>本文表示数</th><th>クリック数</th><th>予約成果</th><th>報酬額</th><th>CTR</th></tr></thead><tbody>'+r[2].map(k=>{let rs=state.history.filter(h=>h[r[0]]===k),i=sum(rs,'impressions'),cl=sum(rs,'clicks'),label=r[0]==='angle'?(ANGLES.find(x=>x[0]===k)||[k,k])[1]:L[k];return '<tr><td>'+label+'</td><td>'+rs.length+'</td><td>'+fmt(i)+'</td><td>'+fmt(cl)+'</td><td>'+fmt(sum(rs,'bookings'))+'</td><td>'+fmt(sum(rs,'reward'))+'</td><td>'+(i?(cl/i*100).toFixed(2)+'%':'未計算')+'</td></tr>'}).join('')+'</tbody></table></div>').join('')}
function clearForm(){if(!$('travel-form'))return;$('travel-form').reset();$('edit-id').value='';$('form-title').textContent='旅行情報を登録';$('experience').value='none';$('verificationStatus').value='unverified'}
function dataFromForm(){let ids=['facilityName','prefecture','region','purpose','targetAudience','attraction','currentPrice','regularPrice','discountAmount','discountRate','targetDate','stayPeriod','bookingDeadline','couponDeadline','campaignPeriod','checkedAt','stayConditions','coupon','couponConditions','campaign','campaignConditions','notes','sourceUrl','affiliateUrl','experience','verificationStatus'],d={};ids.forEach(i=>d[i]=$(i).value.trim());['currentPrice','regularPrice','discountAmount','discountRate'].forEach(i=>{if(d[i]!=='')d[i]=Number(d[i])});return d}
function generate(c,tone='natural',format='reply_link'){let who=c.targetAudience||'旅行を検討している人',place=[c.facilityName,c.region,c.prefecture].filter(Boolean).join('・'),lead=tone==='strong'?'候補に入れてみてもよさそうです。':'条件に合うか、公式情報を確認してみてください。',body=who+'向けに、'+(place||'楽天トラベルの宿泊情報')+'をチェック。\n'+(c.attraction||'公式情報を確認しながら、旅の予定を考えられる情報')+'。\n'+lead,facts=[];if(c.verificationStatus==='verified'){if(c.currentPrice)facts.push('現在料金：'+fmt(c.currentPrice)+'円');if(c.regularPrice)facts.push('通常料金：'+fmt(c.regularPrice)+'円');if(c.discountAmount)facts.push('割引額：'+fmt(c.discountAmount)+'円');if(c.discountRate)facts.push('割引率：'+c.discountRate+'%');if(c.coupon)facts.push('クーポン：'+c.coupon);if(c.bookingDeadline)facts.push('予約期限：'+c.bookingDeadline)}if(format==='direct_link'&&c.affiliateUrl)body+='\n'+c.affiliateUrl;return {body,reply1:[place||'詳細情報',facts.join('／'),c.affiliateUrl||'',c.affiliateUrl?'PR':''].filter(Boolean).join('\n'),reply2:[c.stayConditions,c.couponConditions,c.campaignConditions,c.notes].filter(Boolean).join('\n')}}
function compose(c){let d=drafts[c.id]||{angle:'location',tone:'natural',format:'reply_link'},g=generate(c,d.tone,d.format);drafts[c.id]={...d,...g};let x=drafts[c.id];$('compose-'+c.id).innerHTML='<div class="panel"><h3>投稿内容を作成</h3>'+(c.verificationStatus!=='verified'?'<div class="warning">未確認情報は確定情報として使用していません。</div>':'')+'<div class="grid three"><label>切り口<select data-c="angle" data-id="'+c.id+'">'+ANGLES.map(a=>'<option value="'+a[0]+'" '+(x.angle===a[0]?'selected':'')+'>'+a[1]+'</option>').join('')+'</select></label><label>トーン<select data-c="tone" data-id="'+c.id+'"><option value="natural" '+(x.tone==='natural'?'selected':'')+'>自然</option><option value="strong" '+(x.tone==='strong'?'selected':'')+'>少し強め</option></select></label><label>投稿形式<select data-c="format" data-id="'+c.id+'"><option value="reply_link" '+(x.format==='reply_link'?'selected':'')+'>本文＋リンク付き返信</option><option value="direct_link" '+(x.format==='direct_link'?'selected':'')+'>本文に直接リンク</option><option value="multi_reply" '+(x.format==='multi_reply'?'selected':'')+'>本文＋返信1＋返信2</option></select></label></div><div class="generated"><label>本文<textarea data-t="body" data-id="'+c.id+'" rows="5">'+esc(x.body)+'</textarea><button class="secondary copy" data-tcopy="body" data-id="'+c.id+'">本文をコピー</button><label>返信1<textarea data-t="reply1" data-id="'+c.id+'" rows="4">'+esc(x.reply1)+'</textarea><button class="secondary copy" data-tcopy="reply1" data-id="'+c.id+'">返信1をコピー</button>'+(x.format==='multi_reply'?'<label>返信2<textarea data-t="reply2" data-id="'+c.id+'" rows="4">'+esc(x.reply2)+'</textarea><button class="secondary copy" data-tcopy="reply2" data-id="'+c.id+'">返信2をコピー</button>':'')+'</div><div class="card-actions"><button class="primary" data-a="ready" data-id="'+c.id+'">投稿準備完了として保存</button><button class="secondary" data-a="posted" data-id="'+c.id+'">投稿済みにする</button></div></div>'}
function sync(id){document.querySelectorAll('[data-t][data-id="'+id+'"]').forEach(x=>drafts[id][x.dataset.t]=x.value)}
document.addEventListener('click',e=>{if(e.target.dataset.view)nav(e.target.dataset.view);let a=e.target.dataset.a,id=e.target.dataset.id,c=state.candidates.find(x=>x.id===id);if(a==='compose')compose(c);if(a==='edit'){Object.keys(c).forEach(k=>{if($(k))$(k).value=c[k]??''});$('edit-id').value=id;$('form-title').textContent='旅行情報を編集';nav('travel')}if(a==='delete'&&confirm('この旅行情報を削除しますか？')){state.candidates=state.candidates.filter(x=>x.id!==id);state.history=state.history.filter(x=>x.candidateId!==id);save()}if(a==='ready'||a==='posted'){sync(id);if(a==='posted'&&c.affiliateUrl&&!/PR|※PR/.test((drafts[id].body||'')+(drafts[id].reply1||''))){notice('アフィリエイトURLがあるため、PR表示を入れてください。');return}c.status=a==='posted'?'posted':'ready';c.angle=drafts[id].angle;c.tone=drafts[id].tone;c.format=drafts[id].format;c.post={...drafts[id]};if(a==='posted'){c.postedAt=new Date().toISOString();c.metrics=c.metrics||{};state.history=state.history.filter(h=>h.candidateId!==id);state.history.push({...c,candidateId:id,postFormat:c.format,mainPost:c.post.body,postedAt:c.postedAt})}save();notice(a==='posted'?'投稿済みとして記録しました。':'投稿準備完了として保存しました。')}if(e.target.classList.contains('copy')){sync(id);let text=drafts[id][e.target.dataset.tcopy]||'';if(!text){notice('コピーする内容がありません。');return}navigator.clipboard?.writeText(text).then(()=>notice('コピーしました')).catch(()=>notice('コピーできませんでした'))}if(e.target.id==='export-btn'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='rakuten-travel-backup.json';a.click();$('backup-status').textContent='JSONを保存しました。'}});
document.addEventListener('input',e=>{if(e.target.dataset.t)drafts[e.target.dataset.id][e.target.dataset.t]=e.target.value;if(e.target.dataset.metric){let c=state.candidates.find(x=>x.id===e.target.dataset.id);c.metrics=c.metrics||{};c.metrics[e.target.dataset.metric]=e.target.value===''?null:Number(e.target.value);state.history=state.history.map(h=>h.candidateId===c.id?{...h,metrics:c.metrics}:h);localStorage.setItem(KEY,JSON.stringify(state));renderStats();renderAnalysis()}});
document.addEventListener('change',e=>{if(e.target.dataset.c){drafts[e.target.dataset.id][e.target.dataset.c]=e.target.value;compose(state.candidates.find(x=>x.id===e.target.dataset.id))}});
$('travel-form').addEventListener('submit',e=>{e.preventDefault();let d=dataFromForm(),id=$('edit-id').value;if(d.sourceUrl&&!/^https?:\/\//.test(d.sourceUrl)||d.affiliateUrl&&!/^https?:\/\//.test(d.affiliateUrl)){notice('URLはhttp://またはhttps://で入力してください。');return}if(id)Object.assign(state.candidates.find(x=>x.id===id),d);else state.candidates.push({...d,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'draft',metrics:{}});save();clearForm();nav('candidates');notice('旅行情報を保存しました。')});
['new-btn','cancel-edit','candidate-new'].forEach(id=>$(id).addEventListener('click',()=>{clearForm();nav('travel')}));
$('import-file').addEventListener('change',e=>{let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d||!Array.isArray(d.candidates)||!Array.isArray(d.history)||!Array.isArray(d.sales)||typeof d.settings!=='object')throw Error();if(confirm('現在のデータを読み込んだデータで置き換えますか？')){state=d;save();$('backup-status').textContent='JSONを復元しました。'}}catch(x){$('backup-status').textContent='JSONを読み込めませんでした。既存データは変更していません。'}};r.readAsText(e.target.files[0])});
const DIRECT_API_ENDPOINT='https://openapi.rakuten.co.jp/engine/api/Travel/KeywordHotelSearch/20260731';
function setupDirectApiTest(){const form=$('direct-api-test-form'),button=$('direct-api-test-button');if(!form||!button)return;button.addEventListener('click',async e=>{e.preventDefault();const result=$('direct-api-test-result'),applicationId=$('direct-api-application-id').value,accessKey=$('direct-api-access-key').value,keyword=$('direct-api-keyword').value.trim();if(!applicationId||!accessKey||!keyword){result.textContent='入力不足：Application ID、Access Key、検索キーワードを入力してください。';return}result.textContent='通信中...';const params=new URLSearchParams({applicationId,accessKey,keyword,format:'json'});try{const response=await fetch(`${DIRECT_API_ENDPOINT}?${params.toString()}`);if(!response.ok){let code='取得できないエラー',description='';try{const body=await response.json();if(typeof body?.error==='string')code=body.error;else if(typeof body?.error?.code==='string')code=body.error.code;if(typeof body?.error_description==='string')description=body.error_description;const mask=value=>String(value).replace(applicationId,'[applicationId]').replace(accessKey,'[accessKey]');code=mask(code);description=mask(description)}catch{}result.textContent=`通信失敗\nHTTP status: ${response.status}\nerror: ${code}\nerror_description: ${description||'未取得'}\nCORSエラー: なし`;return}const body=await response.json(),items=Array.isArray(body?.hotels)?body.hotels:[],basicInfo=items[0]?.hotel?.[0]?.hotelBasicInfo;result.textContent=`通信成功\nHTTP status: ${response.status}\n取得件数: ${items.length}\n先頭施設名: ${basicInfo?.hotelName||'未取得'}\nhotelNo: ${basicInfo?.hotelNo||'未取得'}`}catch(error){result.textContent=`通信失敗\nHTTP status: 未取得\nCORSエラー: ${error instanceof TypeError?'あり':'不明'}\nエラー概要: ブラウザから楽天APIへ接続できませんでした。`}})}
setupDirectApiTest();
nav('dashboard');render();
